= Spring

Spring упрощает создание корпоративных приложений с использованием Java. Он предоставляет все необходимое для использования языка Java в корпоративной среде, в том числе поддержку Groovy и Kotlin в качестве альтернативных языков в JVM, а также предлагает гибкость для создания множества видов архитектур в зависимости от потребностей приложения.

== IoC (Inversion of control)

IoC также известен как DI (dependency injection - внедрение зависимостей).
Это процесс, при котором объекты определяют свои зависимости только через аргументы конструктора, аргументы фабричного метода или свойства, которые устанавливаются на экземпляр объекта после его создания или возврата фабричным методом. Затем контейнер внедряет эти зависимости при создании бина. Данный процесс по своей сути является инверсией (отсюда и название, инверсия контроля (Inversion of Control)) самого бина, самостоятельно контролирующего создание или размещение его зависимостей с помощью прямого построения классов или такого механизма, как шаблон локатора служб (Service Locator).

Способы описания зависимости классов:

* Через конструктор (лучше для обязательных зависимостей)
* Через сеттер (для НЕ обязательных зависимостей))
* Через

Основные пакеты:

* org.springframework.beans
* org.springframework.context

Ключевые классы:

* BeanFactory - интерфейс, который предоставляет расширенный механизм конфигурации, способный управлять объектами любого типа (обеспечивает основу конфигурации и базовый функционал).
* ApplicationContext - подинтерфейс BeanFactory, который добавляет более специфичную корпоративную функциональность. ApplicationContext представляет IoC-контейнер Spring и отвечает за создание экземпляра, настройку и компонование бинов. Контейнер получает инструкции о том, какие объекты создавать, конфигурировать и компоновать путем считывания конфигурационных метаданных. (?)

TIP: В Spring объекты, которые составляют основу приложения и управляются IoC-контейнером Spring, называются бинами (beans). Бин (bean) - это объект, который создается, компонуется и управляется IoC-контейнером Spring.