= Цитаты

Цитаты из книг, журналов, статей, которые я счёл полезными.

Шаблон для копирования:
* «.»


== Джен Синсеро
=== «Ни Сы»
* «Ты не виноват в том, какой ты "недодуманный", но ты будешь виноват, если таким и останешься.»
* «Все мы связаны с этой беспредельной силой, но большинство использует её лишь крохотную частицу.»
* «Перед каждым делом спрашивай себя: "Зачем?", "Для чего?" И только потом делай.»
* «Представь, что ты инопланетянин в своём теле! Представил?! А теперь вперёд!»
* «Помните, что сделанное - лучше сказанного.»
* «Целый месяц я готовила кабинет, в итоге написала книгу на кухне...»
* «Мы на цыпочках идём по жизни, надеясь безопасно дотянуть со смерти» $
* «Мы часто притворяемся, что приняли решение, когда в действительности решили лишь попытаться, пока не почувствовали себя неуютно.»
* «Новое решение должно быть абсолютно герметично (от сомнений).»
* «Для мудрого человека каждый день начинается новая жизнь.»
* «Делай что можешь и будь, что будет.» $
* «Незыблемые ценности плавятся при увеличении температуры на 1 градус.»
* «Долго находясь в одном обществе - ты консервируешься в одной плоскости мышления.»
* «Когда вы впервые заберётесь на велосипед, вы неизбежно с него упадёте.»

== Дженни Хольцер
* «Ты жертва правил, по которым живёшь.»

== Никола Тесла
* «Если хочешь узнать тайны вселенной, мысли в терминах энергии, частоты и вибрации.»

== Марк Твен
* «За свою долгую жизнь я пережил много неприятностей, многие из которых так и не случились.»

== Уинстон Черчиль
* «Успех состоит в том, чтобы идти от неудачи к неудаче, не теряя энтузиазма.»

== Марк Аврелий
* «Наша жизнь есть, что ты о ней думаешь.»

== Монтель (франц. философ)
* «Человек не так страдает от того, что случилось, как от своего мнения по поводу случившегося.»

== Авраам Линкольн
* «Большинство людей счастливы настолько, насколько они настроены быть счастливыми.»

== Томас Шелби (Персонаж сериала «Острые козырьки»)
* «Каждая катастрофа это также возможность.»

== Чарльз Кеттеринг
* «Точно определённая проблема - это уже наполовину решённая проблема.»

== Чед Фаулер
=== «Программист-фанатик»
* «Я думаю, что глубоким старцем на смертном одре я оглянусь на свою жизнь и скажу: "Да, это было захватывающее приключение", а не "Ну зато я чувствовал себя комфортно".»

== Исаак Ньютон
* «Если я видел дальше других, то лишь потому, что я стоял на плечах гигантов.»

== Малкольм Гладуэлл
* «Чтобы достичь совершенства в чём-то, человеку нужно около 10 000 часов занятий.» (Неважно язык С++ или игра на фортепиано)

== Алвин Тоффлер
* «Неграмотными людьми 21-го века будут не те, кто не умеет читать и писать, а те, кто не умеет учиться и переучиваться.»

== Евгений Черешнев
=== «Форма жизни №4»
* С точки зрения информатики жизнь можно разделить на три революционные формы:
- Первая форма - микроорганизмы. Они рождаются в форме определяемой их ДНК, а их поведение запрограммировано на строго определённое поведение.
- Вторая форма - человек разумный. Человек рождается в теле, жёстко запрограммированном ДНК (не может выбрать рост, цвет глаз, волос и т.д.), но может улучшать свои мыслительные качества сам.
- Третья форма - искусственный интеллект. Форма, которой можно задавать и модифицировать как "тело", так и "софт".
- Четвёртая форма - ...

//#TODO: дочитать главу и закончить.
* Существует три этапа эволюции ИИ:
- Artificial narrow intelligence (ANI) - узконаправленный ИИ. Условно умные машины: голосовые помощники, умный боты, беспилотные автомобили, компьютерное зрение и т.д. Это работа, которую ИИ уже может делать лучше человека.
- Artificial general intelligence (ANI) - общий ИИ. Уровень ИИ, когда машина может выполнять любую работу, которую способен делать человек, причём не хуже него. (Google)
- Artificial super intelligence (ANI) - искусственный суперинтеллект.

* «Система образования сегодня работает по формуле "подготовить максимальное количество трудоспособных индивидуумов X к возрасту Y со знаниями Z" - при этом уровень знаний должен отличаться минимально...»


== Курс "JavaRush"
* «Лучшим критерием ваших знаний и успехов будут сделанные проекты и успехи на работе, в настоящем деле. Сравнивать себя не с серой массой вокруг, а с рынком и уровнем специалистов, действительно работающих в вашей профессии — это намного правильней.»

== Неизвестный (где-то вычитал)
* «Не важно, что вы знаете. Важно только то, что вы умеете делать полезного другим людям, за что они готовы платить вам деньги. Чем раньше вы это поймете, тем лучше.»