= Цитаты

Цитаты из книг, журналов, статей, которые я счёл полезными.

Шаблон для копирования:
* «.»


== Джен Синсеро
=== «Ни Сы»
* «Ты не виноват в том, какой ты "недодуманный", но ты будешь виноват, если таким и останешься.»
* «Все мы связаны с этой беспредельной силой, но большинство использует её лишь крохотную частицу.»
* «Перед каждым делом спрашивай себя: "Зачем?", "Для чего?" И только потом делай.»
* «Представь, что ты инопланетянин в своём теле! Представил?! А теперь вперёд!»
* «Помните, что сделанное - лучше сказанного.»
* «Целый месяц я готовила кабинет, в итоге написала книгу на кухне...»
* «Мы на цыпочках идём по жизни, надеясь безопасно дотянуть со смерти» $
* «Мы часто притворяемся, что приняли решение, когда в действительности решили лишь попытаться, пока не почувствовали себя неуютно.»
* «Новое решение должно быть абсолютно герметично (от сомнений).»
* «Для мудрого человека каждый день начинается новая жизнь.»
* «Делай что можешь и будь, что будет.» $
* «Незыблемые ценности плавятся при увеличении температуры на 1 градус.»
* «Долго находясь в одном обществе - ты консервируешься в одной плоскости мышления.»
* «Когда вы впервые заберётесь на велосипед, вы неизбежно с него упадёте.»

== Дженни Хольцер
* «Ты жертва правил, по которым живёшь.»

== Никола Тесла
* «Если хочешь узнать тайны вселенной, мысли в терминах энергии, частоты и вибрации.»

== Марк Твен
* «За свою долгую жизнь я пережил много неприятностей, многие из которых так и не случились.»

== Уинстон Черчиль
* «Успех состоит в том, чтобы идти от неудачи к неудаче, не теряя энтузиазма.»

== Марк Аврелий
* «Наша жизнь есть, что ты о ней думаешь.»

== Монтель (франц. философ)
* «Человек не так страдает от того, что случилось, как от своего мнения по поводу случившегося.»

== Авраам Линкольн
* «Большинство людей счастливы настолько, насколько они настроены быть счастливыми.»

== Томас Шелби (Персонаж сериала «Острые козырьки»)
* «Каждая катастрофа это также возможность.»