= Технические книги

Технические книги, которые я прочитал, их краткое описание и фрагменты.

== Чед Фаулер «Программист-ФАНАТИК»
Книга состоит из списка советов, которые должны помочь в развитии разработчика:

=== [Часть 1 | Найди свой рынок]

 [Совет 1 | Будь впереди или погибнешь]
Необходимо всегда иметь актуальные знания в актуальных технологиях, все время развиваться и держать руку на пульсе. Иначе не быть среди лучших.

 [Совет 2 | Предложение и спрос]
Необходимо развиваться в тех направлениях, которые востребованы и в то же время есть нехватка кадров, что характеризуется более высокой оплатой труда.
«Среднестатистические индийские фирмы никогда не занимаются нестандартными технологиями. Они не первопроходцы и, как правило, не склонны к риску. Они дожидаются стабильной ситуации на рынке сервисных услуг, а затем дестабилизируют этот рынок относительно дешёвой рабочей силой.»

 [Совет 3 | Умение писать код мало]
Не всегда имеет смысл разбираться "глубоко" в одной технологии, иногда более важно развивать "в ширину", т.е. расширять кругозор. Очень ценным качеством разработчика являются его бизнес-знания, его понимание направления разработки с точки зрения бизнеса.

 [Совет 4 | Будь худшим]
Речь о том, что нужно всегда находиться в окружении более образованных, развитых в конкретном правлении людей.

 [Совет 5 | Ивестриуй в интеллект]
Как технический специалист, необходимо развиваться в разных направлениях пусть и не глубоко, но разносторонне. Это позволит видеть "картинку" более целостно и с разных сторон. Хорошо бы быть зназкомым с разными паттернами, разными языками программирования, разными подходами программирования и т.д.

 [Совет 6 | Не слушай родителей]
Банальная история про "ведро с крабами", риски, необходимость пробовать и пытаться, не смотря на чужие мнения.

 [История про основание GitHub]*
Чед Фаулер однажды предстал перед выбором: 300к работая в Microsoft или рискнуть и отдать всего себя собственному проекту. Так появился GitHub.

 [Совет 7 | Будь универсалом]
Универсалы более широко мыслят, более целостно смотрят на картину, более всесторонне подходят к решению задачи, они встречаются редко и поэтому высоко ценятся. Будь универсалом.

 [Совет 8 | Будь специалистом]
"Как бы вы написали на Java программу, которая уронит виртуальную машину Java? А в ответ тишина..." Надо разбираться в технологиях, с которыми работаешь. Знания не должны быть поверхностными. Требуются люди, которые в 80% случаях говорят, что им это уже знакомо, глубина знаний которых, поможет им решить проблему и в остальных 20%.
Разберись как работает виртуальная машина, что такое компиляция, откуда берутся внешние библиотеки... Эти знания помогут тебе стать настоящим специалистом.

 [Совет 9 | Не клади все свои яйца в чужую корзину]
Коротко: Необходимо сначала ставить цели, а потом подбирать и осваивать подходящие инструменты, а не сначала изучать инструменты, а потом искать, где их можно применить.

 [Совет 10 | Полюби или уходи]
Без энтузиазма к работе не будет значительного роста. Нужно заниматься тем, что тебе нравится и так, как тебе комфортно. Возможно тебе подходят маленькие коллективы, а возможно, большие компании, может тебе требуеся творческий процесс, а возможно, рутина.
В начале рабочего дня отмечай шкалу энтузиазма к работе от 0 до 10 и с течением времени наблюдай, как меняется динамика. Делай выводы.

=== [Часть 2 | Инвестируя в свой продукт]

 [Совет 11 | Учимся ловить рыбу]
При работе задавай себе вопросы "Как?" и "Почему?": "Как это работает?", "Почему это работает так?" Это поможет тебе не игнорировать пробелы в знаниях, а восполнять их.
Выделяй себе в течении рабочего дня немного времени на изучение чего-то полезного.

 [Совет 12 | Разберись как работает бизнес]
IT продукты нацелены на зарботок или экономию денег. Нужно понимать как именно ваш продукт это делает? Какие факторы влияют на чистую прибыль? Что такое чистая прибыль. Чтобы приносить пользу компании, важно это понимать. Ты не сможешь помогать бизнесу творчески, не зная, как он устроен.
Рекомендация : Книга Стивена Силбигера "MBA за 10 дней".

 [Совет 13 | Найди наставника]
Наставник поможет тебе в отборе и структурировании необходимых знаний, решении проблем. С хорошим наставников твой рост будет в разы быстрее.
Если с этим есть трудности, тогда найди себе пример и постарайся следовать его пути развития, характеристикам, навыкам. Определи в чем ты от него не отстаёшь, а в чём уступаешь, а затем построй план навёрстывания.

 [Совет 14 | Стань наставником]
Если хочешь что-то изучить, попробуй научить этому кого-то другого. Это очень старый и действенный способ. Не обязательно строить систему "учитель-ученик", достаточно просто помогать кому-то в развитии каких-то навыков, знаний.

 [Совет 15 | Практика, практика и ещё раз практика]
Как и в любой деятельности, для развития в программировании (и в целом в IT) необходима регулярная практика.
Рекомендации:
- TopCoder
- Code Kata

 [Совет 16 | Подход к работе]
Осваивай новые методики и подходы разработки ПО. Старайся их практивовать, используя индивидульные преимущества.
Рекомендации:
- Project Managment Book of Knowledge
- Six Sigma

 [Совет 17 | На плечах гигантов]
Есть много разработчиков высокого уровня, есть много продуктов высокого уровня реализации - пользуйся! Учись на их примерах. Изучение чужого кода позволит тебе найти много ответов на вопросы и хороших примеров. Используй чужой код для оценки собственных способностей.
Рекомендации:
- Книга "Приёмы объектно-ориетированного проектирования. Паттерны проектирования"

 [Совет 18 | Автоматизация задач]
Ориентироваться стоит не на технологии, а на решения. Ценность технологии состоит в том, чтобы решать актуальные задачи, обеспечивая измеримую выгоду.
Рекомендации: Исследуй архитектуру, управляемую моделями (Model-Driven Architecture, MDA). Попробуй, поработай, примени.

=== [Часть 3 | Исполнение]
Всё о чём писалось до этого - не более чем подготовка, но наступит момент, когда нужно будет сделать что-то реальное.

 [Совет 19 | Прямо сейчас]
Закон Паркинсона гласит: «Работа заполняет всё отпущенное на неё время». Всегда будет тем, кто спрашивает: "А что мы можем сделать прямо сейчас".
Задача поставленная на Хакатоне выполняется в разы быстрее той, что поставлена в офисе. Рабочий процесс и лишняя рутины сильно тормозит выполнение.

 [Совет 20 | Читай чужие мысли]
Трюк с "телепатией" применими и к руководству, и к заказчикам. Наводящая информация (вопросы, обсуждения) даёт возможность добавлять функциональные возможности, о которых заказчик только собирается попросить или о которых он попросил бы, если бы считал это возможным.
Сделав задачу до того, как тебя о ней попросили (больше или раньше) ты привлечёшь к себе положительное внимание.

 [Совет 21 | Ежедневные победы]
Ежедневно фиксируй цели и результаты их достижения, выходящие за рамки поставленных задач или сроков. Постарайся на планировании спринта, выделить отдельно для себя задачу, которую ты готов выполнить дополнительно. В случае успеха сообщи команде\руководству.

 [Совет 22 | Помни, на кого работаешь]
Слабый совет, больше про общение с начальством и его довольством.

 [Совет 23 | Будь на своём месте]
Сотрудник, мысленно находящийся на большей должности (строящей планы о ней), справляется плохо с обязанностями текущими.  Человеку всегда будет мало. Каждая новая ступень будет порождать новые амбиции. Это чувство не покинет тебя никогда.
При концентрации на настоящем, продвижение к цели осуществляется куда продуктивнее, чем при концентрации на планах.

== Вайсфельд «Объектно-ориентированное мышление»

== Роберт Мартин «Чистый код»

== Алан Тьюринг «Вычислительные машины и разум»
Алан Тьюринг задаётся вопросом: "Может ли машина мыслить" ? Для того чтобы ответить на этот вопрос, автор сравнивает мышление человека и обработку информации компьютером.
Даёт определение терминам "мышление" и "мыслить". Приводит аргументы теорий как в пользу утвердительного ответа на этот вопрос, так и отрицательного.

== Евгений Черешнев «Форма жизни №4»
