= Технические книги

Технические книги, которые я прочитал, их краткое описание и фрагменты.

== Чед Фаулер «Программист-ФАНАТИК»
Книга состоит из списка советов, которые должны помочь в развитии разработчика:

=== [Часть 1 | Найди свой рынок]

 [Совет 1 | Будь впереди или погибнешь]
Необходимо всегда иметь актуальные знания в актуальных технологиях, все время развиваться и держать руку на пульсе. Иначе не быть среди лучших.

 [Совет 2 | Предложение и спрос]
Необходимо развиваться в тех направлениях, которые востребованы и в то же время есть нехватка кадров, что характеризуется более высокой оплатой труда.
«Среднестатистические индийские фирмы никогда не занимаются нестандартными технологиями. Они не первопроходцы и, как правило, не склонны к риску. Они дожидаются стабильной ситуации на рынке сервисных услуг, а затем дестабилизируют этот рынок относительно дешёвой рабочей силой.»

 [Совет 3 | Умение писать код мало]
Не всегда имеет смысл разбираться "глубоко" в одной технологии, иногда более важно развивать "в ширину", т.е. расширять кругозор. Очень ценным качеством разработчика являются его бизнес-знания, его понимание направления разработки с точки зрения бизнеса.

 [Совет 4 | Будь худшим]
Речь о том, что нужно всегда находиться в окружении более образованных, развитых в конкретном правлении людей.



== Вайсфельд «Объектно-ориентированное мышление»

== Роберт Мартин «Чистый код»

