= Аннотация Transactional

== Правила отката транзакции
Если не настроены правила отката транзакции, то по умолчанию, откат происходит при RuntimeException и Error.

== Параметры
* isolation - определяет уровень изоляции
* noRollbackFor - определяет типы исключений, которые не должны вызывать откат транзакции
* propagation - определяет тип распространения транзакции
* readOnly - транзакция Эффективно доступен только для чтения, что позволяет проводить соответствующую оптимизацию во время выполнения.true

== Режимы mode
* AdviceMode.PROXY - стандартный механизм создания proxy-объектов (по умолчанию)
* AdviceMode.ASPECTJ - механизм, при котором, при компиляции будет сгенерирован код так, что тело метода будет уже обернуто кодом, управляющим транзакцией.

== Распространение транзакции Propagation
* MANDATORY - Поддержите текущую транзакцию, создайте исключение, если ее нет.
* NESTED - Выполнение во вложенной транзакции, если текущая транзакция существует.
* NEVER - Выполнять без транзакции, создавать исключение, если транзакция существует.
* NOT_SUPPORTED  - Выполняйте транзакции без транзакций, приостановите текущую транзакцию, если она существует.
* REQUIRED - Поддержите текущую транзакцию, создайте новую, если ее нет. (По умолчанию)
* REQUIRES_NEW - Создайте новую транзакцию и приостановите текущую транзакцию, если она существует.
* SUPPORTS - Поддерживайте текущую транзакцию, выполняйте ее без транзакции, если она не существует.

== Особенности и советы
* Нельзя вызывать метод с аннотацией @Transactional в рамках того же класс (она не будет работать)
* Метод с аннотацией @Transactional должен быть только public
* По умолчанию @Transactional не откатит транзакцию из-за Exception, используй RuntimeException (для Exception можно настроить через параметр)
* @Transactional занимает соединение с БД. Сложную логику лучше выносить за пределы транзакции

== Суть
* Если Spring обнаруживает аннотацию @Transactional на бобе, он создаёт динамический прокси этого боба.
* Прокси имеет доступ к менеджеру транзакций (PlatformTransactionManager / TransactionManager) и будет просить его открывать и закрывать транзакции/соединения.
* Сам менеджер транзакций будет просто делать то, что вы делали в разделе "Обычный Ява": Управлять старым добрым соединением СБДЯ (JDBC).