= Самый богатый человек в Вавилоне. Джордж Клейсон

== Глава 1. Человек, пожелавший золота
История о том, как два бедных друга пошли за советом как разбогатеть к третьему богатому.

* «Мы преуспели в том, что мы делаем, и пора двигаться дальше. Теперь нам нужное особое знание, которое наполнит наши кошельки золотом и серебром.»

== Глава 2. Самый богатый человек в Вавилоне
* «Не заслуги побуждают судьбу улыбнуться вам. Если вы не разбогатели за свою долгую жизнь = так только потому, что никогда не пытались узнать законов богатства. А если и узнавали - не спешили им следовать.»
* «Обучение - это два процесса. Сперва мы узнаём новое - то, о чём не знали раньше. А после мы можем применить это знание, сформировав навык.»
* «Вы, юнцы, считаете наши уроки скучными, бесполезными, настолько же безнадёжно устаревшими, как и мы сами. Но солнце сегодня такое же, как было при твоём отце и при его отце, и оно будет точно таким же, когда отойдут во тьму твои внуки.»
* «Мы юнцов - метеоры. Озаряют небо на секунду и исчезают без следа в вечности. Мудрость стариков же - звёзды, чей свет неизменен, и он никуда не уйдёт.»
* «Всё, что ты тратишь на свои нужды, тебе не принадлежит. Но всё, что ты откладываешь - становится твоим рабом. Каждый медяк, каждый золотой сикель - твой раб.»
* «Совет, вещь бесплатная, но если ты обратишься за ним не по адресу - плата за него может быть велика.»

== Глава 3. Семь заплат для дырявого кошелька
=== Первый принцип - "Начни кормить свой кошелёк"
* "Из девяти монет, попадающих в твой кошелёк, трать только девять."

=== Второй принцип - "Контролируй свой расходы"
* "Ограничивай свои траты и составляй бюджет расходов."

=== Третий принцип - "Позволь своему золоту множиться"
* "Богатство - это тот поток золота, который поступает в ваши кошельки со стороны. Это доход."
* "Заставь каждую монету приносить доход."

=== Четвёртый принцип - "Береги свои вложения от потерь"
* "Береги свои накопления, избегай ненадёжных вложений и сделок, обещающих скорую и небывалую прибыль."

=== Пятый принцип - "Стань обладателем собственного дома"

=== Шестой принцип - "Позаботься о безбедном будущем"
* "Любой человек с маломальским капиталом должен думать о будущем, ведь оно неизменно настанет."
* "Заранее позаботься о том, чтобы будущее, где ты уже старик, было безбедным для тебя и твоей семьи."

=== Седьмой принцип - "Совершенствуй свой навык зарабатывать деньги и будь достойным человеком"
* "Я хочу разбогатеть - но что это значит? Это желание абстрактно и размыто."
* "Я хочу заработать 5 сикелей" - это уже конкретная цель.
* "Если ты научишься зарабатывать 5 золотых, этого у тебя уже не отнять - можно двигаться дальше."

* -- "А если я хочу и пять золотых сикелей, и стадо овец, и новую накидку... ?"
* -- "Все твои желания перепутаются и будут мешать друг другу. Ты будешь постоянно хотеть всего этого, но не увидишь пути ни к одной цели."

* "Совершенствуйтесь. Развивайте свои навыки и учитесь, обрастайте мудростью и будьте достойным человеком."

== Глава 4. Приветствуйте госпожу Удачу
* "... если ты не опускаешь руки и продолжаешь своё дело, со временем ты всё больше ощущаешь, что удача на твоей стороне. Ты непременно добьёшься успеха."
* "Первая возможность, которую подкидывает нам госпожа Удача - это принять решение о том, чтобы сколотить состояние. Пораскинуть мозгами и поставить себе цель."
* Удача не любит тугодумов. Она хочет, чтобы ей отвечали скоро и шли навстречу быстро.
* "Госпожа Удача любит тех, кто действует. Удача - это возможности, которые мы не упустили."
* "Время для хорошей сделки - сейчас!"
* "Стоит лишь раз распознать врага, который живёт у тебя внутри, и с ним уже можно будет бороться." (про вредные привычки)

== Глава 5. Пять законов золота
* "Увы, самую тяжкую память нам дают случаи, когда мы должны были что-то сделать, но не сделали."

== Глава 6. О долгах и должниках. Истории из сундука
* "Хочу стать торговцем и разбогатеть! - Желания его ясны, а вот цели туманны."
* "Щепотка предусмотрительности многим лучше мешка сожалений."

== Глава 7. Торговец верблюдами из Вавилона
* "Если у тебя душа раба, ты станешь им, и неважно, кем ты был рождён."
* "У тебя душа рабаЮ если ты продолжаешь сидеть здесь и причитать о своей судьбе. «Я ничего не могу поделать» - это проявление рабской души."
* "Свободный человек не может жить вот так, зная, как много ему в жизни предстоит исправить - он ищет способы сделать это."
* "Если ты свободен настолько, чтобы решиться, — всегда найдётся способ пройти этот путь."
