= Индивидуальный план развития

От 3 марта до ~ 1 июля = ~ 4 месяца -> 8 спринтов

== Спринт 23.11
Системная аналитика: Знать предметную область Аналитические задачи "Озера данных"
* изучить направление "Управление метаданными"
* изучить направление  "Управление ETL-процессами"

Разработка: Иметь теоретические знания и опыт использования базовых конструкций языка Java
* иметь теоретические знания и  наличие опыта использования: Интерфейс, Класс, Объект, их отличия; встроенные типы; передача объектов через параметры; модификаторы доступа; перегрузка операций; исключения, аннотации
* иметь теоретические знания и  наличие опыта использования: неизменяемые объекты;  способы инициализации объекта; наследование, альтернатива множественному наследованию
* иметь теоретические знания и  наличие опыта использования: Создание аннотаций; рефлексия; StreamAPI (отличия от обычного цикла); Lombok.
* иметь теоретические знания и  наличие опыта использования: неизменяемые классы (java8 и 8+)
* иметь теоретические знания и  наличие опыта использования: методы интерфейса
* иметь представление о работе технологии Lombok

== Спринт 23.13
Системная аналитика: Уметь формулировать требования к разработке
Разработка: Иметь знания об инструментарии Spring Framework

== Спринт 23.15
Системная аналитика: Знать функциональную структуру платформы ОД и КУС
Разработка: Иметь теоретические знания и опыт управления транзакциями в Java-приложении

== Спринт 23.17
Системная аналитика: Уметь осуществлять разработку концепции
Разработка: Понимать, как используется многопоточность java в проекте

== Спринт 23.20
Системная аналитика: Подтвердить базовые технические навыки аналитика I
Разработка: Иметь понимание процесса сборки и доставки ПО

== Спринт 23.22
Системная аналитика: Подтвердить базовые технические навыки аналитика II
Разработка: Иметь знания об инструментарии JOOQ

== Спринт 23.25
Системная аналитика: Иметь навыки тестирования ПО
Разработка: Иметь представление о назначении и использовании технологии Docker

== Спринт 23.27
Системная аналитика: Повторение, закрепление, хвосты.
Разработка: Повторение, закрепление, хвосты.