= Функциональное тестирование

Функциональное тестировать позволяет выявить и минимизировать ошибки в работе продукта до релиза.

== Примеры
* Проверка работоспособности авторизации
* Проверка работоспособности добавления товара в корзину
* Проверка работоспособности оплаты
* Проверка работоспособности заказа доставки

== Отличие функционального и нефункционального тестирования
=== Функциональное тестирование
Функциональное тестирование проверяет ФУНКЦИИ ПРИЛОЖЕНИЯ, которые заложены его логикой работы, т.е. работает ли приложение в целом. Цель функционального тестирования — проверить, верно ли реализованы запланированные функции в продукте.

Функциональное тестирование в себя включает:

* Unit-тестирование
* Интеграционное тестирование
* Системное тестирование
* Приёмочное тестирование

=== Нефункциональное тестирование
Нефункциональное тестирование проверяет, работает ли приложение так, как было задумано, не сами функции, а их МАСШТАБИРУЕМОСТЬ, РАСШИРЯЕМОСТЬ и прочее. К нефункциональным видам тестирования также относят "Нагрузочное тестирование" - осуществление массовых запросов. Цель нефункционального тестирования — проверить, как продукт работает с точки зрения удобства, скорости, безопасности и других важных параметров.

Нефункциональное тестирование в себя включает:

* Нагрузочное тестирование
* Тестирование безопасности
* Тестирование юзабельности
* Тестирование Совместимости

=== Отличие
Функциональное тестирование - это тестирование с т.з. пользователя. Ему не интересно как поведёт себя система при выполнении 1000 запросов или интеграции с чем-то там под капотом.
Пользователю важно, что предоставленная опция и работает и делает ровно то, что ему нужно.

Пример: Опция "положить товар в корзину"

* Функциональное тестирование - возможно ли положить товар в корзину (функциональность работает?)
* Нефункционального тестирования - возможно ли выполнить это действие через мобильное приложение?

== Виды функционального тестирование
* "Черный ящик" - тестирование без доступа к исходному коду, когда тестировщик проверяет приложение как пользователь.
* "Белый ящик" - тестирование с доступом к исходному коду, когда тестировщик понимает, как приложение работает изнутри (более глубокое).

== Уровни глубины функционального тестирования
* Верхний уровень. Тестирование интерфейса - запуск приложения в браузере и проведение запланированных проверок.
* Средний уровень. Тестирование API - обращение к бэкенду, минуя пользовательский интерфейс (через терминал или Postman).
* Нижний уровень. Тестирование баз данных - проверка валидных и невалидных значений с точки зрения бизнес-логики.
* Уровень взаимодействия. Тестирование интеграций - проверка, как приложение взаимодействует с внешними системами (проверка оплаты или доставки - интеграция с платёжными и логистическими системами).

== Деление с точки зрения использование инструментов
* Ручное. Внимательность и заинтересованность тестировщика.
* Автоматизированное - проводится с использованием специальных инструментов.

== Методы функционального тестирования (основные)
=== Положительное тестирование
Проверка положительных сценариев: работает ли система так, как было задумано. Например, получается ли указать адрес при заказе доставки.

=== Негативное (отрицательное тестирование)
Проверяет, как система ведёт себя в нестандартных ситуациях, при введении невалидных значений с точки зрения формата или бизнес-логики. Например, в интернет-магазине пользователь пытается повторно вернуть товар.

=== Техника тест-дизайна
Это готовые стратегии и приёмы, которые позволяют оптимизировать трудозатраты на создание тестов, соответствующих определённым целям и задачам.

== Алгоритм выполнения функционального тестирования
. Шаг 1. Подготовка
.. Изучение принципа работы продукта на тех. уровне. на основе сценариев и документации разработчиков.
.. Проверка требований на непротиворечивость, полноту и атомарность.
.. Проверка на соблюдение требования "один тест - одна проверка".
.. Желательно выполнить до старта разработки.

. Шаг 2. Составление тестовой документации
.. Разработчики приступают к разработке продукта. Тестировщик готовит документацию для тестирования (тестовый сценарий, чек-листы, тест-кейсы).

. Шаг 3. Тестирование продукта
.. Проверка продукта по заранее подготовленным сценариям.
.. Оформление баг-репортов (при наличии ошибок).

== Инструменты
* Тестовая документация. Хранилище знаний о работе системы
* Автотест. Скрипт, который пишет тестировщик самостоятельно для имитации взаимодействия пользователя с приложением с целью выявления возможных ошибок в работе системы.
* Нагрузочное тестирование (Apache JMeter или Яндекс.Танк).
* Панель разработчиков (Chrome DevTools). Для наглядности изучения какие запросы уходят, и какие скрипты выполняются.
* Инструменты для работы с БД (DBeaver, PostgreSQL).