= Виды технических ошибок. Уровни технической поддержки

== Классификация технических ошибок
Ошибка в программировании — это дефект кода, баг, который может вызывать в программе сбои и неожиданное поведение.

=== По степени влияния

* Blocker — блокирующий баг. Программа запускается, но спустя время баг останавливает ее выполнение. Чтобы снова пользоваться программой, блокирующую ошибку в коде устраняют.
* Critical — критический баг. Нарушает функциональность программы. Появляется в разных частях кода, из-за этого основные функции не выполняются.
* Major — существенный баг. Не нарушает, но затрудняет работу основного функционала программы либо не дает функциям выполняться так, как задумано.
* Minor — незначительный баг. Слабо влияет на функционал программы, но может нарушать работу некоторых дополнительных функций.
* Trivial — тривиальный баг. На работу программы не влияет, но ухудшает общее впечатление. Например, на экране появляются посторонние символы или всё рябит.

=== По приоритету

* Top — наивысший. Такой баг — суперсерьезный, потому что может обвалить всю программу. Его устраняют в первую очередь.
* High — высокий. Может затруднить работу программы или ее функций, устраняют как можно скорее.
* Normal — обычный. Баг программу не ломает, просто где-то что-то будет работать не совсем верно. Устраняют в штатном порядке.
* Low — низкий. Баг не влияет на программу. Исправляют, только если у команды есть на это время

=== По типам

* Логические. Приводят к тому, что программа зависает, работает не так, как надо, или выдает неожиданные результаты — например, не записывает файл, а стирает.
* Синтаксические. Это опечатки в названиях операторов, пропущенные запятые или кавычки.
* Взаимодействия. Это ошибка в участке кода, который отвечает за взаимодействие с аппаратным или программным окружением. Такая ошибка возникает, например, если неправильно использовать веб-протоколы.
* Компиляционные. Любая программа — это текст. Чтобы он заработал как программа, используют компилятор. Он преобразует программный код в машинный, но одновременно может вызывать ошибки.
* Ошибки среды выполнения. Возникают, когда программа скомпилирована и уже выглядит как файл — жми и работай. Юзер запускает файл, а программа тормозит и виснет. Причина — нехватка ресурсов, например памяти или буфера.
* Арифметические. Бывает, в коде есть числовые переменные и математические формулы. Если где-то проблема — не указаны константы или округление сработало не так, возникает баг.

== Уровни технической поддержки
Уровни технической поддержки оговариваются при формировании SLA (Service Level Agreement, оно же Соглашение об уровне сервиса).

Уровни тех. поддержки делятся на:

1. HelpDesk (он же 1-й уровень поддержки), принимающий обращения от всех пользователей компании по телефону, почте и интранету, оформляющий обращения в инциденты и переводящий инциденты в специализированные группы поддержки 2-го уровня.
2. Группа поддержки 2-го уровня из аналитиков, знающих эту систему с точки зрения функционала, которые могут разобрать инцидент, помочь пользователям и выявить ошибки системы в коде/данных.
3. Группа поддержки 3-го уровня из разработчиков, которые умеют исправить код/данные в системе и привлечь вендора базового ПО в случае необходимости.
4. Вендор базового ПО является в этой схеме 4-м уровнем поддержки. На этом же уровне могут фигурировать другие подразделения компании типа сетевиков, инфраструктуры и т.п.

=== Форматы файлов для обмена данными*
YAML (пробелы влияют на структуру)
[source, yaml]
----
yaml:
    attribute: 1
    list:
    - element1
    - element2
    object:
    name: Ali
    age: 25
  map:
  - key1: value
  - key2: value
----

JSON (пробелы не влияют на структуру)
[source, json]
----
{
  "json": {
    "attribute": 1,
    "list": [
      "element1",
      "element2"
    ],
    "object": {
      "name": "Ali",
      "age": 25
    },
    "map": [
      {
        "key1": "value"
      },
      {
        "key2": "value"
      }
    ]
  }
}
----