= Spring в действии. Глава 1

== Spring
Spring предлагает контейнер, который создаёт компонент приложения и управляет ими - контекст приложения.
Bean-компоненты объединяются внутри контекста Spring, образуя полноценно приложение.
Акт объединения bean-компонентов основан на шаблоне "Внедрение зависимостей".

== Spring Boot
Spring Boot - это расширение для Spring, предлагающее несколько улучшений, в том числе автоконфигурацию. (@Autowired позволяет осуществлять автоматическое связывание).

== Аннотации
@SpringBootApplication - указывает, что приложение SpringBoot, а также включает в себя 3 аннотации:

* @SpringBootConfiguration - говорит о том, что это класс конфигурации
* @EnableAutoConfiguration - включает автоконфигурацию SpringBoot
* @ComponentScan - включает сканирование компонентов

@SpringBootTest - настраивает JUnit на запуск теста с поддержкой возможностей Spring Boot.
@WebMvcTest - настраивает поддержку тестирования Spring MVC в Spring.


=== Про Spring Boot Starter зависимости
Spring Boot Starter зав-ти (например, spring-boot-starter-web или spring-boot-starter-thymeleaf), отличаются тем, что они обычно не имеют своего библиотечного кода, а транзитивно подключают другие библиотеки.
Преимущества таких зав-тей:

* Файлы сборки меньше весят им будет легче управлять, так как не нужно объявлять зависимости для каждой библиотеки, которая может понадобиться.
* Освобождают от необходимости следить за версиями библиотек. Версии библиотек однозначно будут совместимы с используемой версией Spring Boot.

=== Про метод main
Метод main() вызывает статический метод run() класса SpringApplication, который выполняет фактическую загрузку приложения, создавая контекст приложения Spring.

=== Про аннотацию @Controller
Аннотация @Controller сама по себе ничего не делает. Её цель - идентифицировать класс, как компонент, доступный механизму сканирования компонентов (т.е. класс с аннотацией @Controller будет создан как bean-компонент в контексте приложения Spring).
Такими же по функции являются аннотации @Component, @Repository, @Service. Их отличие только смысловое - какую роль выполняет класс.

=== Ландшафт Spring
==== Ядро Spring
* Базовый контейнер и инфраструктура внедрения зависимостей.
* Содержит веб-фреймворк Spring MVC
* Поддержка JDBC
* Поддержка реактивного программирования, в том числе новую реактивную веб-инфраструктуру WebFlux^, которая в значительно степени основана на Spring MVC.

==== Spring Boot
* Обеспечивает возможность подключения зависимостей и автоконфигурацию.
* Предоставляет Actuator, который позволяет исследовать работу внутренних механизмов приложения во время выполнения (получение метрик, дампов потоков выполнения и приложения, свойства окружения и т.д.).
* Обеспечивает гибкую спецификацию свойств окружения.
* Обеспечивает дополнительную поддержку тестирования, помимо предоставляемой ядром фреймворка Spring.
* Предлагает альтернативную модель программирования, основанную на сценариях Groovy - Spring Boot CLI^

==== Spring Data
* Позволяет определять репозитории данных для приложений в форме простых интерфейсов Java, используя соглашения об именах при определении методов, реализующих хранение и извлечение данных.
* Может работать с несколькими различными типами БД, включая реляционные, документные, графовые и др.

==== Spring Security
* Обеспечивает механизмы аутентификации, авторизации и защиты API.

==== Spring Integration и Spring Batch
* Обеспечивает возможность интеграции с другими приложениями и компонентами.
* Spring Integration обеспечивает интеграцию в реальном времени, когда данные обрабатываются по мере их поступления.
* Spring Batch обеспечивает ПАКЕТНУЮ интеграцию, когда данные могут собираться в течении какого-то времени, пока не сработает триггер (время, лимит и т.д.)

==== Spring Cloud
* Spring Cloud - набор проектов для разработки облачных приложений на базе Spring.
* Обеспечивает возможность внедрить микросервисную архитектуру.

==== Spring Native
* Позволяет компилировать проекты Spring Boot в двоичные файлы, с помощью компилятора GraalVM. Такие файлы запускаются значительно быстрее и занимают меньше места.


=== Инструмент DevTools
Инструмент DevTools - это набор дополнительных инструментов разработчика приложений на Spring, позволяющих:

* Автоматически перезапускать приложение при изменении кода.
* Автоматически обновлять окно браузера при изменении ресурсов, передаваемых браузеру.
* Автоматически отключать кеширование шаблонов.
* Открывать встроенную консоль H2, если используется БД H2.






