= Spring в действии. Глава 4. Работа с нереляционными данными

== Cassandra
Cassandra – это распределенная, высокопроизводительная, постоянно доступная, в  конечном итоге согласованная база данных NoSQL с секционированным колоночным хранилищем.

Cassandra хранит записи в  таблицах, которые распределены между узлами, находящимися в  отношениях «один ко многим». Ни один узел не хранит все данные, но любую конкретную запись можно получить из нескольких разных узлов, что устраняет любую единую точку отказа.

== Запуск Cassandra
Если у вас еще нет кластера Cassandra для работы, то для нужд разработки вы можете запустить кластер с одним узлом, используя Docker:
[source, bash]
----
$ docker network create cassandra-net
$ docker run --name my-cassandra network cassandra-net -p 9042:9042 -d cassandra:latest
----
Эта команда запустит кластер с одним узлом и откроет порт узла (9042) на хост-компьютере, через который наше приложение сможет получить к нему доступ.

Cassandra оптимизирована для операций чтения. По этой причине обычно желательно, чтобы таблицы были сильно денормализованы, а данные повторялись в нескольких таблицах.