= Spring в действии. Глава 6 Работа с конфигурацией

== Метаданные в Spring
Метаданные в Spring можно хранить в resources\META-INF\additional-spring-configuration-metadata.json

== Профилирование в Spring
Профилирование в Spring это механизм обеспечения уникальных настроек для разных окружений

Способы задания уникальных настроек:

* через переменные окружения (нет возможности следить за изменениями в переменных окружения или быстро откатывать изменения в случае ошибки)
* использовать профили Spring


=== Настройка конфигурационных файлов
....
Профили в Spring – это разновидность условной конфигурации, в которой разные bean-компоненты и конфигурационные классы и свойства применяются
или игнорируются в зависимости от профиля, действующего во время выполнения.

Имя файла можно выбирать в соответствии с паттерном:
application-{имя профиля}.yml или application-{имя профиля}.properties.
Либо, в общем файле соблюдая секционирование
....

=== Установка активного профиля
....
Активный профиль РЕКОМЕНДУЕТСЯ задавать через переменную окружения:
% export SPRING_PROFILES_ACTIVE=prod
Если приложение запускается как выполняемый файл JAR, назначить активный профиль можно, с помощью параметра командной строки, например:
% java -jar taco-cloud.jar --spring.profiles.active=prod

Стоит отметить, что при развертывании приложения Spring в Cloud Foundry автоматически активируется профиль с именем cloud.
....

=== Аннотации поддержки в рамках работы активного профиля
....
Аннотация @Profile позволяет устанавливать на класс или метод метку, что данная логика должна выполнять только в рамках определённого активного
профиля (-ей) или наоборот, только если активный профиль не равен заданному @Profile({"!prod", "!qa"})
....