= Введение в API. Брайан Кукси

Источник: https://systems.education/api-intro#showmore

== Глава 1. Введение
API (application programming interfaces) - интерфейсы прикладного программирования.
API — это инструмент, который делает данные веб-сайта удобными для использования компьютером.

Computer <--> [Website|API] <--> User'

Когда две системы (веб-сайты, настольные компьютеры, смартфоны) соединяются через API, мы говорим, что они «интегрированы».
В интеграции у вас есть две стороны, каждая из которых, имеет особое имя:
* Клиент - сторона, которая получает данные
* Сервер - сторона (мощный компьютер), которая отдаёт данные постредством API (предоставляет сама)


== Глава 2. Протоколы
Протокол - строгий набор правил, которые определяют способ взаимодествия между двумя системами\машинами\компьютерами\серверами.
Bluetooth - один из протоколов подключения устройств.
HTTP - протокол передачи гипертекста (об это указывает браузеру префикс http:)

=== HTTP-запросы
Взаимодействие в HTTP протоколе основано на концепции "Запрос-Ответ".
Для того, чтобы сделать правильный HTTP-запрос, клиент должен указать основные 4 вещи:
* URL - адрес обработки запроса
* Method (GET|POST|PUT|DELETE|other)
* Headers - список заголовков (предоставляют метаинформацию о запросе)
* Body - тело запроса

HTTP-ответ содержит в себе:
* Body - тело запроса
* Headers - cписок заголовков (предоставляют метаинформацию о запросе)
* Код состояния (200/404/...)

== Глава 3. Форматы данных
Чтобы две системы могли общаться по протоколу, в нём должен быть описан формат данных (JSON|XML|other).
Content-Type - заголовок, который описывает в каком формате будут переданы данные не сервер.
Accept-Type - заголовок, который описывает в каком формате будет получен ответ клиентом.

== Главы 4-5. Аутентификация
Аутентификация - механизм подверждения личности.

== Базовая аутентификация
Базовая аутентификация требует только имя пользователя и пароль.
Клиент берет эти два учетных данных, смешивает их вместе, чтобы сформировать единое значение, и передает его в запросе в заголовке HTTP под названием «Авторизация» (Authorization).

Плюсы:
* Прост в использовании и разработке
* Существует готовый заголовок, так как Basic Auth является установленным стандартом.

Недостатки:
* Используется одна и та же пара (логин, пароль) как для доступа к API, так и для управления УЗ.

== Аутентификация через ключ
Аутентификация через ключ - метод проверки пользователя, который представляет собой использование длинной последовательности символов (букв и цифр).

Плюсы:
* Позволяет предоставлять ключ под конкретные доступы

Недостатки:
* Нет стандарта в использовании (ключ может быть в заголовке\теле\адресе и т.д.)

== Открытая Авторизация
Открытая Авторизация (OAuth) - механизм проверки прав, который осуществляет автоматизацию обмена ключами между клиентов и сервером.

Ключевые объекты в OAuth:
* Пользователь — человек, который хочет связать два веб-сайта.
* Клиент — веб-сайт, которому будет предоставлен доступ к данным пользователя.
* Сервер — веб-сайт, на котором хранятся данные пользователя.

Базовый принцип работы: (для веб-сайта, а для моб. приложений может отличаться)

Шаг 1. Пользователь сообщает клиенту о необходимости подключения к серверу.

Шаг 2. Клиент направляет пользователя на сервер.
В перенаправлении содержится информация об адресе (callback URL), на который сервер отправит пользователя после успешной аутентификации

Шаг 3. Пользователь входит на сервер и получает клиентский доступ.
Сервер убедился, что пользователь зарегистрирован, значит информацию об этом нужно вернуть клиенту.

Шаг 4. Сервер отправляет пользователя обратно клиенту вместе с кодом.
Сервер отправляет пользователя обратно клиенту (на URL-адрес обратного вызова из шага 2). В ответе скрыт уникальный код авторизации для клиента.

Шаг 5. Клиент обменивает Код + секретный Ключ на Токен доступа.
Клиент берет полученный код авторизации и делает еще один запрос к серверу. Этот запрос включает секретный ключ клиента.
Когда сервер видит действительный код авторизации и секретный ключ доверенного клиента, он уверен, что клиент является тем, кем он себя называет, и что он действует от
имени реального пользователя. Сервер отвечает токеном доступа.

Шаг 6. Клиент получает данные с сервера
На этом этапе клиент может получить доступ к серверу от имени пользователя. Маркер доступа из шага 6 — это, по сути, еще один пароль для учетной записи пользователя на сервере.
Клиент включает токен доступа в каждый запрос, чтобы он мог аутентифицироваться напрямую с сервером.

Клиент обновляет токен (необязательно)
Функция, представленная в OAuth 2 — это возможность истечения срока действия токенов доступа. Это полезно для защиты учетных записей пользователей за счет усиления безопасности —
чем быстрее истекает срок действия токена, тем меньше времени может быть злонамеренно использован украденный токен, подобно тому, как срок действия номера кредитной карты
истекает через определенное время. Срок службы токена устанавливается сервером. API на практике могут использовать срок от часов до месяцев.
По истечении срока службы клиент должен запросить у сервера новый токен.

== Отличия между OAuth1 и OAuth2
В OAuth2 токены доступа имеют срок действия.
OAuth1 включает дополнительный шаг. Между шагами 1 и 2, описанными выше, OAuth 1 требует, чтобы клиент запросил у сервера токен запроса. Этот токен действует как код авторизации в OAuth 2 и обменивается на токен доступа.
OAuth1 требует, чтобы запросы были подписаны цифровой подписью. Подписание запроса — это способ защитить данные от подделки при их передаче между клиентом и сервером. Подписи позволяют серверу проверять подлинность запросов.

Большая часть API-трафика происходит по уже защищенному каналу (HTTPS). Понимая это, OAuth 2 устраняет подписи, стараясь упростить использование второй версии. Дело в том, что OAuth 2 полагается на другие меры для обеспечения безопасности передаваемых данных.

== Авторизация
Элементом OAuth 2, заслуживающим особого внимания, является концепция ограничения доступа, официально известная как авторизация.
На шаге 2, когда пользователь нажимает кнопку, чтобы разрешить доступ клиенту, где-то глубоко внутри скрываются те самые разрешения, которые запрашивает клиент.
Эти разрешения, называемые областью действия (scope), являются еще одной важной функцией OAuth 2. Они позволяют клиенту запрашивать ограниченный доступ к данным пользователя, тем самым облегчая пользователю доверие к клиенту.

Что делает область действия действительно мощным инструментом, так это то, что её ограничения связаны с конкретным клиентом. В отличие от ключа API, где ограничения, налагаемые на ключ, одинаково влияют на каждого клиента, область действия OAuth позволяет одному клиенту иметь разрешение X, а другому — разрешения X и Y. Это означает, что один веб-сайт может просматривать ваши контакты, а другой сайт может просматривать и редактировать их.


== Глава 6. Проектирование API
=== Архитектура
Архитектура API бывает:
* SOAP - архитектура API, известная стандартизированными форматами сообщений.
* REST - архитектура API, ориентированная на управление ресурсами.

Ресурс - это собирательное название, куда входит адрес, метод, параметры запроса и т.д.

== Глава 7. Связь в реальном времени
Интеграции - механизм, который позволяет осуществить обмен данными между системами.
Интеграции бывают:

* управляемые клиентом - это когда пользователь взаимодействуйте с клиентом и хочет, чтобы данные на сервере обновились
* управляемые сервером - это когда пользователь делает что-то на сервере и требует, чтобы клиент знал об этом.

Как правило, клиент - это единственный кто можете инициировать общение, так как клиент делает запросы, а сервер отвечает.

=== Интеграция, управляемая клиентом
Пример интеграции управлемой клиентом:
Есть система заказа пиццы.
- Приложение для заказа пиццы - это клиент
- API для заказа пиццы - сервером
Когда пользователь нажимает кнопку заказа пиццы - клиент в виде приложения обращается к серверу по его API.

=== Интеграция, управляемая сервером
Виды интеграций, управляемых сервером:

* Опрос - многократный запрос ресурса с коротким интервалом на предмет обновления (статуса например)
* Долгий опрос - опрос, но с отложенным ответом, сервер отвечает только тогда, когда что-то изменилось.
* Вебхуки - это когда клиент отправляет запросы и сам же прослушивает их (клиент тоже становится сервером). Веб-перехватчики используют
URL обратного вызова и шлют туда ответ, когда на сервере происходит изменение. 1 запрос - 1 обновление.

Спецификация HTTP-подписок, Restful Webhooks, REST Hooks и PubSubHubbub -  все эти решения пытаются определить процесс подписки, в котором клиент может сообщить серверу, какие события ему интересны и по какому URL-адресу обратного вызова отправлять обновления.

== Глава 8. Заключение
Ничего особенного