= Логирование

== Библиотеки для логирования
* log4j
* JUL — java.util.logging
* JCL — jakarta commons logging
* Logback
* SLF4J — simple logging facade for java

=== log4j
В log4j были возможности по конфигурации таким образом, чтобы можно было включить логирование в пакете com.example.type и выключить его в подпакете com.example.type.generic. Это позволяло быстро отсечь то, что нужно логировать, от того, что не нужно.
log4j добавил такое понятие как appender, то есть инструмент, с помощью которого записываются логи и layout — форматирование логов. Это позволяет записывать только то, что нужно и как нужно. Больше о appender поговорим чуть позже.

TIP: Есть две версии log4j: 1.2.х и 2.х.х, которые несовместимы друг с другом.


=== JUL — java.util.logging
Одно из ключевых преимуществ это решения — JUL включен в JDK (Java development kit). К сожалению, при его разработке за основу взяли не популярный log4j, а решение от IBM, что и повлияло на его развитие. По факту на данный момент JUL есть, но им никто не пользуется.
Из “такого себе”: в JUL уровни логирования отличаются от того, что есть в Logback, Log4j, Slf4j, и это ухудшает понимание между ними.

=== JCL — jakarta commons logging
Из-за того, что долгое время не было промышленного стандарта в логировании и был период, когда многие создавали свой кастомный логгер, решили выпустить JCL — общую обертку, которая  использовалась бы над другими.
К сожалению, обертка была очень бедна на функциональность и никаких дополнений не вносила.

=== Logback
Logback написал тот же разработчик, что и log4j, чтобы создать ему преемника. В основе была та же идея, что и в log4j.

Отличия были в том, что в logback:

* Улучшена производительность.
* Добавлена нативная поддержка slf4j.
* Расширена опция фильтрации.

Стандартно logback не требует каких-либо настроек и записывает все логи начиная от уровня DEBUG и выше. Если нужна настройка, ее можно выполнить через xml конфигурацию.

=== SLF4J — simple logging facade for java

Где-то в 2006 году один из отцов-основателей log4j вышел из проекта и создал slf4j — Simple Logging Facade for Java — обертку вокруг log4j, JUL, common-loggins и logback.
Она делится на две части: API, который используется в приложении и реализация, которая добавляется отдельными зависимостями для каждого вида логирования.

Slf4j поддерживает все новые функции, такие как форматирование строк для логирования. До этого была такая проблема.
У slf4j не было проблем совместимости с JDK и API, поэтому сходу возникло красивое решение:

log.debug("User {} connected from {}", user, request.getRemoteAddr());
На данный момент это лучшее решение.

=== Что нужно логировать
Разумеется, логировать все подряд не стоит. Например, если залогировать чьи-то личные данные, то это плохо.

Но есть и то, что логировать обязательно:

* Начало/конец работы приложения. Нужно знать, что приложение действительно запустилось, как мы и ожидали, и завершилось так же ожидаемо.
* Вопросы безопасности. Здесь хорошо бы логировать попытки подбора пароля, логирование входа важных юзеров и т.д.
* Некоторые состояния приложения. Например, переход из одного состояния в другое в бизнес процессе.
* Некоторая информация для дебага, с соответственным уровнем логирования.
* Некоторые SQL скрипты. Есть реальные случаи, когда это нужно. Опять-таки, умелым образом регулируя уровни, можно добиться отличных результатов.
* Выполняемые нити(Thread) могут быть логированы в случаях с проверкой корректной работы.

=== Популярные ошибки в логировании
* Избыток логирования. Не стоит логировать каждый шаг, который чисто теоретически может быть важным. Есть правило: логи могут нагружать работоспособность не более, чем на 10%. Иначе будут проблемы с производительностью.
* Логирование всех данных в один файл. Это приведет к тому, что в определенный момент чтение/запись в него будет очень сложной, не говоря о том, что есть ограничения по размеру файлов в определенных системах.
* Использование неверных уровней логирования. У каждого уровня логирования есть четкие границы, и их стоит соблюдать. Если граница расплывчатая, можно договориться какой из уровней использовать.
* Логирование приватных данных.

=== Уровни логирования
* OFF: никакие логи не записываются, все будут проигнорированы;
* FATAL: ошибка, после которой приложение уже не сможет работать и будет остановлено, например, JVM out of memory error;
* ERROR: уровень ошибок, когда есть проблемы, которые нужно решить. Ошибка не останавливает работу приложения в целом. Остальные запросы могут работать корректно;
* WARN: обозначаются логи, которые содержат предостережение. Произошло неожиданное действие, несмотря на это система устояла и выполнила запрос;
* INFO: лог, который записывает важные действия в приложении. Это не ошибки, это не предостережение, это ожидаемые действия системы;
* DEBUG: логи, необходимые для отладки приложения. Для уверенности в том, что система делает именно то, что от нее ожидают, или описания действия системы: “method1 начал работу”;
* TRACE: менее приоритетные логи для отладки, с наименьшим уровнем логирования;
* ALL: уровень, при котором будут записаны все логи из системы.

TIP: Уровни на примере log4j. Остальные решения, кроме JUL, используют такие же уровни.
Получается, что если в приложении в каком-то месте включен уровень логирования INFO, будут логироваться все уровни, начиная с INFO и до FATAL. Если будет уровень логирования FATAL, будут записаны только логи с этим уровнем.