= Брокеры сообщений

В сложных системах, приложения декомпозируются на элементы и этим элементам нужно как-то взаимодействовать между собой.
Для осуществления взаимодействия между модулями(сервисами, компонентами) системы существуют брокеры сообщений.
Грамотная настройка коммуникации позволяет компонентам ставить друг другу задачи, сообщать об изменениях, уведомлять другие части логики о своём состоянии.

== Apache Kafka
Механизм обмена сообщений добавляет некоторые трудности в обслуживании:

* вероятность превышения ресурса для пересылки сообщений.
* зависимость компонентов от отказоустойчивости и корректности работы брокера сообщений.
* потеря данных в шине может запутать или нарушить состояние системы.

Для решения этих проблем была создана Apache Kafka - сверхнадёжная, сверхмасштабируемая, сверхгибкая распределённая система обмена сообщениями внутри бекэнд-приложений.

=== Преимущества Kafka

* это распределённая система (серверы объединяются в кластеры, т.е. хранение и пересылка сообщений идёт параллельно на разных серверах) - надёжность и отказоустойчивость
* легко масштабируется горизонтально ввиду своей архитектуры (достаточно вводить новые серверы) - заточен под рост производительности.
* записи в Kafka хранятся в виде журнала коммитов, из-за чего в очередь сообщений можно добавлять данные, но нельзя изменять или удалять - надёжность и прозрачность изменений
* есть репликация данных, хранение сообщений на диске, роутинг данных по разным параметрам и другое.

=== Где используют Kafka

* связь между микросервисами
* организация потоков данных (идёт поток событий, которые нужно передавать по цепочке и на каждом этапе выполнять с ними какое-то действие)
* агрегация записей (можно писать данные быстрее, чем в БД, можно организовать сбор разных метрик, делать вычисления, фиксировать результат вычислений в БД)
* сбор логов (можно использовать для кратковременного (часы, сутки) хранения логов)