= Тестирование

== JUnit
Постановка:

- Аннотации junit (sql  и др. которые не часто использую я)
- Mockito + как используется у нас (mock\verify\spy)

=== Основные аннотации до Junit 5:
* @Test – определяет что метод method() является тестовым.
* @Before – указывает на то, что метод будет выполняться перед каждым тестируемым методом @Test.
* @After – указывает на то что метод будет выполняться после каждого тестируемого метода @Test
* @BeforeClass – указывает на то, что метод будет выполняться в начале всех тестов, а точней в момент запуска тестов(перед всеми тестами @Test).
* @AfterClass – указывает на то, что метод будет выполняться после всех тестов.
* @Ignore – говорит, что метод будет проигнорирован в момент проведения тестирования.

=== Основные аннотации Junit 5:
* @BeforeEach - Аннотированный метод будет запускаться перед каждым тестовым методом в тестовом классе.
* @AfterEach - Аннотированный метод будет запускаться после каждого тестового метода в тестовом классе.
* @BeforeAll - Аннотированный метод будет запущен перед всеми тестовыми методами в тестовом классе. Этот метод должен быть статическим.
* @AfterAll - Аннотированный метод будет запущен после всех тестовых методов в тестовом классе. Этот метод должен быть статическим.
* @Test - Он используется, чтобы пометить метод как тест junit.
* @DisplayName - Используется для предоставления любого настраиваемого отображаемого имени для тестового класса или тестового метода
* @Disable - Он используется для отключения или игнорирования тестового класса или тестового метода из набора тестов.
* @Nested - Используется для создания вложенных тестовых классов
* @Tag - Пометьте методы тестирования или классы тестов тегами для обнаружения и фильтрации тестов.
* @TestFactory - Отметить метод - это тестовая фабрика для динамических тестов.


== Mockito
JUnit используется для структурирования тестов и выполнения утверждений (assertions), в то время как Mockito предоставляет механизмы для создания моков и шпионов,
которые необходимы для изоляции тестируемого кода от его зависимостей.

В Spring Boot, Mockito используется для создания моков или спай-объектов для Spring Beans. Это позволяет имитировать поведение этих бинов, таким образом,
чтобы тестировать взаимодействие различных слоев приложения (например, контроллеров, сервисов и репозиториев) без необходимости взаимодействовать с реальными внешними системами,
такими как базы данных.

Используйте, @Mock когда вы хотите просто протестировать функциональность извне, фактически не вызывая этот метод.
Используйте, @Spy когда вы хотите протестировать функциональность внешне + внутренне с помощью самого вызываемого метода.

Если вы хотите напрямую заглушить методы зависимости, то смоделируйте эту зависимость (@Mock).
Если вы хотите заглушить данные в зависимости, чтобы все ее методы возвращали нужные вам тестовые значения, то шпионьте за этой зависимостью (@Spy).