- Изучение принципов работы WEB приложений (cookie, структура http запросов, stateless)
- Изучение (базовых уровень) ограничений прав доступа (JWT)
- Изучение стандарта OAuth 2.0
- Реализовать проект, с использованием OAuth 2.0

== Отличие Stateless и Stateful
* Stateless - архитектура запроса, при которой, вся информация требуемая для выполнения запроса серверу описана в самом запросе.
Например: Запрос, где пользователь каждый раз вынужден указывать в заголовке запроса token авторизации.

* Stateful - архитектура запроса, при которой сервер хранит данные о пользователе между запросами. Усложняет масштабирование
Например: Сервер запоминает данные авторизации и cookie пользователя, и при повторном запросе не запрашивает аутентификацию и настройки стилей.

== JWT
JSON Web Token - это JSON-объект, созданный для безопасной передачи информации между двумя участниками.

=== Принцип работы
1. Пользователь обращается к серверу аутентификации передавая ему логин и пароль (или др. аутентификационный ключ)
2. Сервер аутентификации на основе аутентификационного ключа (логина и пароля) создаёт JWT и отправляет его пользователю
3. Пользователь при обращении к API приложения (серверу приложения), добавляет в запрос JWT
4. Сервер приложения по токену проверяет, является ли пользователь тем, за кого себя выдаёт.

=== Структура JWT
* Header (Заголовок) - содержит информацию о том, как должна вычисляться JWT-подпись.
* Payload (Полезные данные) - содержит полезные данные, называемые jwt-claims. [НЕ ШИФРУЕТСЯ!]
* Signature (Подписи) - кодирует header и payload, затем соединяет их и хешурует алгоритмом, заданным в header

В итоге JWT выглядит так: header.payload.signature

=== Нюансы JWT
* Использование JWT не скрывает и не маскирует данные автоматически.
* Данные в JWT закодированы и подписаны, но не зашифрованы.
* Цель кодирования данных - преобразование структуры.
* Цель подписи - проверка аутентификации источника данных.
* Цель шифрования - защита данных от неавторизированного доступа.
* JWT не гарантирует безопасность чувствительных данных.
* Секретный ключ должны знать и сервер авторизации и сервер приложения. Тогда они оба могут сформировать подпись и сравнить их между собой.

=== Преимущества JWT
* Не нужно хранить информацию о всех выданных токенах, как при классической схеме с сессиями.
* Приложению не нужно заниматься выдачей и валидацией токенов, это может на себя взять сервер аутентификации.
* При использовании отдельного сервиса аутентификации возможно организовать SSO - единую точку входа в разные сервисы.
* Приложение может хранить в payload разные данные.


== OAuth 2.0
OAuth 2.0 - стандарт безопасности (протокол авторизации), который позволяет одному приложению получать разрешение на доступ к данным в другом приложении.

В OAuth участвует следующие элементы:

* Resource Owner - Владелец аккаунта.
* Client - Само приложение, услуги которого нам интересны
* Authorization Server - приложение, которое знает resource owner-а и в котором у этого owner-а уже есть УЗ.
* Resource Server - API или сервис, которым клиент воспользоваться от имени Resource Owner-а.
