= Предметная область Аналитические задачи "Озера данных"

Платформа ОД - это программный комплекс, предоставляющий средства разработки, конфигурирования, оркестрации и мониторинга выполнения ETL-процессов с использованием готового ETL-инструментария и разрабатываемых прикладных ETL-компонентов бизнес-трансформации данных.
Платформа ОД использует экосистему Hadoop для управления вычислительными ресурсами и организации хранения больших объемов данных, а для хранения и управления всеми метаданными - СУБД PostgresPro.

== Направление "Управление метаданными"

Метаданные - это информация о другой информации. Метаданные в платформе ОД - это данные о сущностях в БХД платформы, данные о внешних системах и сущностях, используемых в ETL-процессах платформы, конфигурация ETL-процессов в виде метаописаний потоков задач и задач.
БХД - Блок хранения данных платформы ОД - это система хранения данных в табличной форме и в виде файлов. Система хранения данных в таблицах Hive и файлах HDFS.
Данные в БХД загружаются с целями хранения исходных данных, их обработки, хранения обработанных данных, использования исходных и обработанных данных для построения витрин и агрегатов, выгрузки данных во внешние системы для дальнейшего использования. Пространство БХД делится на логические слои, например, слой исходных данных, слой сырых данных, слои прикладных витрин и агрегатов и т.д.

КУС - Компонент управления сервисами является программным решением по управлению изолированными логическими функциональностями Блока управления метаданными (БУМ), реализуемых в виде модулей и называемых Сервисами БУМ.
Управление сервисами включает в себя регистрацию, конфигурирование запуска и параметров запуска, группировку, отслеживание статуса работы, и оперативное управление состоянием Сервисов БУМ

Реализация: Сервис УМО (внутри КУС)

== Направление "Управление ETL-процессами"
ETL (от англ. Extract, Transform, Load — дословно «извлечение, преобразование, загрузка») — один из основных процессов в управлении хранилищами данных, ETL – общий термин для всех процессов миграции данных из одного источника в другой (другие связанные с этим термины – экспорт, импорт, конвертация данных, парсинг файлов, web-scrapping и пр.), который включает в себя:
* извлечение данных из внешних источников;
* их трансформация и очистка, чтобы они соответствовали потребностям бизнес-модели;
* и загрузка их в хранилище данных.

ETL-процесс - это последовательность ETL-операций над данными и других действий с целью загрузки, преобразования и выгрузки данных. ETL-процесс в платформе ОД состоит из одного или нескольких потоков задач.
ETL-процесс в платформе ОД - это один или несколько потоков задач, состоящих из задач перемещения данных от источника к приёмнику и их метаданных, а также технических операций не связанных с обработкой данных.

ETL-инструмент в платформе ОД - это исполняемый модуль, выполняющий одну из ETL-операций или другие действия, и предназначенный для многократного использования в разных ETL-процессах.
ETL-инструменты в платформе ОД представлены исполняемыми модулями импорта данных из внешних систем-источников и экспорта данных во внешние системы-приемники. К ETL-инструментам также относятся инструменты ведения технической истории изменений данных в ОД и другие инструменты.

ETL-инструментарий в платформе ОД - это совокупность самих ETL-инструментов, а также библиотек, используемых в разработке и тестировании прикладных ETL-компонентов бизнес-трансформаций данных средствами платформы ОД.

Прикладной ETL-компонент в платформе ОД - это исполняемый программный модуль, разрабатываемый для решения частной задачи бизнес-трансформации данных какого-либо прикладного проекта, например, для построения витрины данных.

Задача в платформе ОД - это часть ETL-процесса, описание применения одного из ETL-инструментов или прикладного ETL-компонента в рамках определенного потока задач. Задача может иметь индивидуальные условия запуска. Во время подготовки задачи к запуску создаётся объект запуск задачи в журнале запусков задач.
Поток задач в платформе ОД - это логическое бизнес-объединение задач, позволяющее накладывать общие условия запуска на задачи в потоке задач и отслеживать общий статус выполнения запусков задач в экземпляре потока задач.
Открытый экземпляр потока задач разрешает запуск входящих в этот поток задач в рамках данного экземпляра, но задачи потока могут иметь и индивидуальные условия запуска в дополнение к общим. В момент открытия потока создаётся экземпляр потока в журнале экземпляров потоков. Платформа предоставляет возможность настраивать как последовательное, так и параллельное выполнение запусков задач в экземпляре потока. Поток задач можно отключить, тогда он не откроется даже при выполнении всех его условий запуска.
Поведение задачи настраивается с помощью параметров, указывающих на исполняемый модуль и библиотеки, на необходимое количество вычислительных ресурсов, на метаданные о системах-источниках и системах-приемниках, на метаданные о сущностях-источниках и о сущностях-приемниках данных и т.д.

Реализация: Сервис Оркестрации (внутри КУС) ?