= Требования к разработке

== Что такое требования к разработке
Требования к программному обеспечению — совокупность запросов/утверждений относительно свойств или качеств программной системы, подлежащей реализации.
Создаются в процессе проработки (анализа и синтеза) задания на разработку/модернизацию программного обеспечения (ПО).

Бизнес-потребность-> Бизнес-требование-> Бизнес-правила

== Для чего формулируют требования к разработке
Требования к разработке формулируют, для того чтобы описать и зафиксировать представление о том, что нужно сделать.

== Отличие требования от дизайна
Термин проект (дизайн) обычно используется именно для технических вариантов решения, которые создаются непосредственно специалистами по реализации: разработчиками программного обеспечения, ИТ-архитекторами и т.д.
А требование означает выдвигаемые бизнесом условия или ожидаемые возможности.

== Что включают в себя требования к разработке (Feature Description)
. Ответы на вопросы:
.. Зачем? Какова цель? В чем польза для бизнеса?
.. Почему? Каковы риски? Что мы потеряем, если не сделаем? Что случится, если сделаем?
.. Что? Какую проблему мы хотим решить? Для кого?
.. Как? Функциональные требования и сценарий использования (последовательность действий)
. Словарь терминов предметной области
. Раздел "Согласование" (Заказчики, Исполнители друг друга поняли)
. Вспомогательные метрики
.. Definition of Done - кратко, как понять, что фича работает.
.. Нефункциональные требования (Например: скорость реакции UI, загрузка бэкэнда, ограничения CPU и оперативной памяти и т.д.)
.. Требования к безопасности (Например: шифрование, хранение персональных данных и т.д.)
.. Corner Case - тестирование граничных случаев (Например: что будет, если цена товара 0?)
.. Частотность сценариев - определение, какие сценарии встречаются чаще.
.. Требования к мониторингу и сбору метрик.
.. Зависимости фичей - помогают правильнее распределять ресурсы. (Например: нельзя реализовать “возможность оплаты картой Мир”, пока мы не сделали фичу “выбор метода оплаты”)

== Классификация требований
. Бизнес-требования
- Формулировка целей, задач и результатов, которые описывают, почему изменение было инициировано
- Могут относиться к предприятию в целом, области бизнеса или конкретной инициативе
- Отвечает на вопросы: "почему это нужно?", "зачем я это хочу?"

. Требования заинтересованной стороны
- Описывают потребности заинтересованных сторон, которые необходимо удовлетворить, чтобы выполнить БИЗНЕС-ТРЕБОВАНИЯ
- Могут служить "мостом" между бизнес-требованиями и требованиями к решению
- Отвечает на вопрос: "кому что нужно?"

. Требования к решению (системе)
- Описывают возможности и качества решения, отвечающего требованиям заинтересованных сторон
- Обеспечивают необходимый уровень детализации, позволяющий разработать и внедрить решение
- Отвечает на вопрос: "что я хочу?"
- Делятся на функциональные и нефункциональные:

.. Функциональные требования к решению (системе)
- Описывают возможность, которой должно обладать решение с точки зрения поведения
- Описывают информацию, с которой решение будет работать
- Описывают поведение

.. Нефункциональные требования к решению (системе)
- Описывают условия, при которых решение должно оставаться действенным
- Описывают качества, которыми решение должно обладать
- Описывает особенности эксплуатации и выражается в измеримых показателях

. Переходные требования
- Описывают возможности, которыми должно обладать решение или условия, которым оно должно соответствовать, чтобы обеспечить переход из текущего состояния в будущее
- Имеют временный характер (т.е. отпадают после завершения изменения)
- Решают такие вопросы как конвертация данных, обучение, обеспечение непрерывности бизнеса
- Отвечает на вопрос "Каковы условия реализации перехода от бизнес-потребности к внедренному решению?"

=== Отличие функциональных и нефункциональных требований

Функциональные требования объясняют, что должно быть сделано, в них перечислены действия приложения, как реакция на действия Актора.
Эти требования реализуются в перечисленных Use Scenarios (сценариях использования).

Нефункциональные требования фиксируют условия, при которых решение должно оставаться эффективным, или качества, которыми решение должно обладать.
Самые распространенные примеры нефункциональных требований:

* Масштабируемость
* Надёжность
* Минимальное время простоя
* Методы поддержки

Функциональные требования это про:

- Глаголы
- Обязательность
- Product feature
- Легкость в снятии

Нефункциональные требования это про:

- Атрибуты
- Не обязательность
- Product properties
- Трудно

=== Примеры
Примеры требований по BABOK:

* Бизнес-требование: Увеличить продажи на 10% в следующем квартале
* Требование заинтересованной стороны: Клиенты должны иметь возможность отслеживать статус своего заказа онлайн
* Функциональное требование: Система должна генерировать уникальный номер для каждого заказа и отправлять его клиенту по электронной почте
* Нефункциональное требование: Система должна обрабатывать не менее 1000 заказов в час с временем отклика не более 5 секунд
* Переходное требование: Система должна поддерживать импорт данных из старой базы данных в формате CSV
* Определительное бизнес-правило: Обращения привилегированных клиентов получают наивысший приоритет
* Поведенческое бизнес-правило: Обращение привилегированного клиента должно быть обработано оператором в течение 1-го часа после его поступления независимо от дня недели и времени суток

== Управление жизненным циклом требований
Цель управления жизненным циклом требований — удостовериться в том, что требования бизнеса, требования заинтересованных сторон,
требования к решению и дизайны согласуются друг с другом, и что решение их реализует. Это включает контроль над требованиями, а
также над тем, как требования будут реализованы в реальном решении, подлежащем построению и поставке. Это также помогает обеспечить
доступность информации бизнес-анализа для использования в будущем.

- Начинается: с представления бизнес-потребности в качестве требования
- Выполняется: в ходе разработки решения
- Заканчивается: когда решение и представляющие его требования перестают использоваться

TIP: Управление требованиями не заканчивается по окончании реализации решения. При правильном управлении, требования продолжают
приносить пользу на протяжении всей жизни решения.


=== Состав процесса "Управление жизненным циклом требований"
Область знаний "Управление жизненным циклом требований" включает следующие задачи:

* Трассировка требований: анализирует и поддерживает отношения между требованиями, дизайнами, компонентами решения и другими рабочими продуктами для проведения анализа влияния, покрытия и размещения.
* Поддержание требований: обеспечивает правильность и актуальность требований и дизайнов в течение жизненного цикла и помогает их использовать повторно там, где это уместно.
* Приоритизация требований: оценивает пользу, срочность и риски, связанные с конкретными требованиями и дизайнами, чтобы убедиться, что работа по анализу и/или поставке решения в каждый момент времени ведется над самыми важными из них.
* Оценка изменений требований: оценивает новые и изменяющиеся требования заинтересованных сторон для определения необходимости их отработки в рамках изменения.
* Одобрение требований: работа с заинтересованными сторонами, вовлеченными в процесс управления, для достижения одобрения и согласия относительно требований и дизайнов.


== Трассировка требований
Потребность-> Бизнес-требование-> Требование заинтересованных сторон-> Требования к решению-> Дизайн(Проект решения)

== Как сформулировать требования (на основе странички Дениса)

=== Что такое требование
Требование — это утверждение, которое выражает или описывает потребность и связанные с ней ограничения и условия.
TIP: Требование может быть записано в форме естественного языка или какой-либо другой формы языка.
TIP: Если заявление выражено в форме естественного языка, оно должно включать подлежащее и глагол вместе с другими элементами, необходимыми для адекватного выражения информационного содержания требования.
В требовании должны быть указаны:

* Предмет требования (например, система, программное обеспечение и т. д.)
* Что должно быть сделано (например, работать на уровне мощности, обеспечить поле для)
* Ограничение на систему.
Таблицы условий-действий и варианты использования — это другие средства регистрации требований.
Важно заранее договориться о конкретных ключевых словах и терминах, которые сигнализируют о наличии требования.

=== Общий подход.
Требования, которые являются обязательными, используют слово «должен».
Нетребования, такие как описательный текст, используют такие глаголы, как «есть» и «был». Лучше избегать использования термина «должен» из-за возможного неправильного истолкования как требования.
Заявления о фактах, будущем или декларация цели являются необязательными, необязательные положения используют слово «будет». «Будет» также может использоваться для установления контекста или ограничений использования.
Предпочтения или цели, которые являются желательными или необязательными используют слово «следует». Это не требования.
Предложения или допущения не являются обязательными, необязательными положениями и используют «может».
Используйте позитивные утверждения и избегайте негативных требований, таких как «не следует».
Используйте активный залог: избегайте использования пассивного залога, например, «требуется, чтобы».
Избегайте использования таких терминов, как «должен быть в состоянии».
TIP: Требования в agile могут использовать альтернативные формулировки, такие как пользовательские истории, без явного использования термина «должен». См. ISO/IEC/IEEE 12207:2017, Приложение "H" для дополнительно обсуждения по agile.
TIP: Все термины, характерные для разработки требований, должны быть формально определены и должны последовательно применяться во всех требованиях системы.

== Структура требований
Должны быть чётко сформулированы и разработаны:

- Требования заинтересованных сторон;
- Требования к системе;
- Требования к элементам системы.

Эта практика способствует проверке требований с заинтересованными сторонами и помогает гарантировать, что требования точно отражают потребности заинтересованных сторон.


Правильно сформулированное конкретное требование содержит одно или несколько из следующего:

* Оно должно быть выполнено или реализовано системой для решения проблемы, достижения цели или удовлетворения потребности заинтересованной стороны;
* Оно определяется измеримыми условиями;
* Оно имеет ограничения;
* Оно определяет производительность системы при использовании конкретной заинтересованной стороной или соответствует возможностями системы, но не возможности пользователя, оператора или другого заинтересованного лица;
* Его можно проверить (например, можно продемонстрировать реализацию требования в системе).

TIP: Дополнительным соображением является то, что требования на более низких уровнях согласуются с проектом системы более высокого физического уровня.



=== Формат требований
Это описание обеспечивает средства для различения требований и атрибутов этих требований (условий, допущений и ограничений).

  Формат:
"[Условие][Cубъект][Действие][Объект][Ограничение действия]"

  Примеры:
Когда сигнал X получен[Условие], система[Субъект] должна установить[Действие] признак получения сигнала X[Объект] в течение 2 секунд[Ограничение действия]
При волнении моря 1[Условие] радиолокационная система[Cубъект] должна обнаруживать[Действие] цели[Объект] на расстоянии до 100 морских миль[Ограничение действия]

  Формат:
"[Cубъект][Действие][Ограничение действия]"

Система учета[Cубъект] должна отображать ожидающие счета-фактуры клиентов[Действие] в порядке возрастания даты счета-фактуры[Ограничение действия]

Условия — это измеримые качественные или количественные атрибуты, которые предусмотрены для требования. Они дополнительно квалифицируют требование необходимое требование, и предоставляют атрибуты, которые позволяют сформулировать и установить требование таким образом, чтобы его можно было подтвердить и проверить. Условия могут ограничивать возможности разработчика дизайна приложения. Важно преобразовать потребности заинтересованных сторон в требования заинтересованных сторон, не накладывая ненужных ограничений на пространство решений.
Ограничения ограничивают проектное решение или реализацию процесса системного проектирования. Ограничения могут применяться ко всем требованиям, могут быть указаны в связи с конкретным требованием
(или набором требований), или могут быть идентифицированы как автономные требования (т. е. не ограничивающие какое-либо конкретное требование).
Примеры ограничений, приводящих к возникновению требований, включают:

* Интерфейсы к уже существующим системам (например, формат, протокол или контент), где интерфейс не может быть изменен;
* Ограничения физического размера (например, контроллер должен помещаться в ограниченном пространстве в крыле самолета);
* Законы конкретной страны;
* Доступная продолжительность или бюджет;
* Уже существующая технологическая платформа;
* Ограничения по техническому обслуживанию;
* Возможности и ограничения пользователя или оператора.

== Заметки
Cамое главное, что Дима будет спрашивать - виды требований, отличие функциональных и нефункциональных + примеры
+ есть страничка Дениса о наименованиях - https://confluence.gnivc.ru/pages/viewpage.action?pageId=84299620

Уметь формулировать требования к разработке.
Изучить раздел требований в документации проекта, в результате:
- Иметь теоретические знания о процессе формирования требований
- Уметь формировать требований для реализации