= Бизнес-аналитика. Концепция

== Бизнес-анализ
Бизнес-анализ - это деятельность, обеспечивающая возможность изменений предприятия через определение потребностей и рекомендацию решений, приносящих пользу заинтересованным сторонам.
Бизнес-анализ помогает предприятию формулировать потребности и обосновывать изменения, а также проектировать и описывать решения.

Бизнес-анализ выполняется в рамках стратегических, тактических или операционных инициатив.

== Бизнес-аналитик

Бизнес-аналитик это человек, которые выполняет описание задач бизнес-анализа, отвечает за выявление, синтез и анализ информации, полученной из различных источников. Отвечает за выявление истинных потребностей
заинтересованной стороны.

Выполняемые бизнес-аналитиками действия включают:

* Выявление и понимание проблем и целей предприятия
* Анализ потребностей и решений
* Разработку стратегий
* Управление изменениями
* Содействие сотрудничеству заинтересованных сторон

== Концепция
Концепция - система взглядов, то или иное понимание явлений, процессов или\и решений. Концепция дает ответ на вопрос - "Как достичь намеченной цели?"
Концепция – не «серебряная пуля», и она не защитит ваш проект от всех коллизий и мутаций. Но она способна свести их к минимуму. Попутно выявляя потенциальные недостатки и векторы развития будущего продукта.

Разработка концепции по BABOK - это процесс определения и документирования целей, области и ограничений проекта, а также выявления и анализа потребностей заинтересованной стороны.
Концепция является одним из ключевых артефактов бизнес-анализа, который помогает сформировать общее видение решения и оценить его целесообразность и реализуемость.
Концепция также служит основой для разработки более детальных требований и дизайна решения.

=== Цели концепции
Цели концепции включают:

* Определение единого информационного поля (однозначное и единое представление о будущем продукте)
* Определение и фиксация границ проекта (что будет в проекте, а чего в нём быть не должно)
* Выявление рисков, недостатков и перспектив продукта (с какими трудностями можно столкнуться, как их преодолеть и в какую сторону развивать продукт)
* Первичная оценка проекта и проектирования (очертить хотя бы базовый горизонт, понять порядок объема ресурсов)

=== Состав концепции
Концепция должна в себя включать:

* Краткое описание проекта
** Чтобы отбросить всё лишнее, сформулировать ядро проекта
** Чтобы обеспечить плавное погружение читателей в вашу документацию
* Цели и задачи бизнеса
* Потребности пользователей
* Описание основной механики
** Какая предполагается функциональность
** Входные и выходные сигнала
** Описание преобразования входного сигнала в выходной
* Состав продукта и его технические особенности
** Прорабатывается примерный состав компонентов и интеграций (внешних и внутренних)
* Ограничения


Состав концепции в ОД:

* Общее описание
* Триггер
* Входной и выходной сигналы
* Интерфейсы функции
* Работа с данными