= Lombok

Это основанная на аннотациях библиотека Java, позволяющая сократить шаблонный код.
Проект Lombok включается прямо в процесс сборки. Затем Lombok автоматически сгенерирует для Java байт-код, который вставляет в файлы .class, необходимые для реализации желаемого поведения, в зависимости от используемых вами аннотаций.

== Аннотации Lombok
* @Getter
* @Setter
* @AllArgsConstructor, @NoArgsConstructor, @RequiredArgsConstructor (@NonNull и неинициализированные final поля)
* @ToString
* @EqualsAndHashCode
* @NonNull
* @Data (включает в себя @ToString, @EqualsAndHashCode, @Getter, @Setter и @RequiredArgsConstructor)
* @Value (для final классов)
* @Cleanup (позволяет гарантировать, что заданный ресурс будет автоматически очищаться перед тем, как покинет актуальную область видимости)
* @Synchronized (действует примерно так же, как synchronized, но защелкивается на особом приватном поле под названием $lock)
* @SneakyThrows (позволяет бесшумно выбрасывать проверяемые исключения, не объявляя их явно в условии throws метода)
* @Builder
* @Log
* @With (добавляет методы для каждого поля, которые делают клон объекта с одним измененным полем)
* @FieldDefaults (задаёт уровень видимости полей и методов: public, private, protected)

== Отключение Lombok
На случай если потребуется отключить Lombok, у него есть инструмент delombok. Он обеспечивает автоматическую генерацию исходного кода Java, содержащего в байт-коде ровно те же возможности, которые внедрялись бы при помощи Lombok. Таким образом, база кода, аннотированная Lombok, просто заменяется стандартной базой кода на Java, без Lombok. После этого весь проект больше вообще не будет зависеть от Lombok.
