== Garbage Collector (Сборщик мусора)
Сборщик мусора - внутренний механизм Java, который отвечает за освобождение памяти, то есть удаление из нее ненужных объектов.

=== Типы объектов
Для сборщика мусора все объекты делятся на два типа:

* Достижимые (Если на объект есть хотя бы одна ссылка, он считается достижимым)
* Недостижимые (Если нет ни одной переменной, которая ссылается на объект, такой объект считается недостижимым и объявляется мусором: значит, его можно удалять)

Объект считается достижимым, если на него ссылается другой достижимый объект. Получается такая “цепочка достижимости”. Она начинается при запуске программы и тянется в течение всего времени ее работы.

=== Хранение объектов
Все объекты в Java хранятся в специальной области памяти, которая называется куча (heap).
Куча, где хранятся все созданные объекты, разделена на несколько частей

==== Young Generation ("молодое поколение")
Область памяти в куче для свежих объектов. Состоит из двух следующих частей.

===== Eden
Первая часть хранения - Eden ("Райский сад"). Сюда попадают все объекты, сразу после создания.

====== Survival Space
Вторая часть хранения - Survival Space ("Место для выживших"). Сюда попадают все объекты, пережившие сборку мусора.
Survival Space в свою очередь делится на поколения. Каждый объект относится к своему поколению в зависимости от того, сколько сборок мусора он пережил. Если одну — он относится к "Поколению 1", если 5 — к "Поколению 5".

==== Old Generation ("старое поколение")
Область памяти в куче для "объектов-долгожителей", переживших несколько сборок мусора.

=== Сборка мусора

==== Фрагментация памяти
Структурирование ячеек памяти на фрагменты.
Пояснение: При создании, удалении объектов, в структуре памяти появляется множество разбросанных свободных ячеек. Получается, что память вроде бы есть, но определённого свободного значимого "фрагмента" памяти нет.

==== Дефрагментация
Для решения проблем с дырами во фрагментах памяти существует процесс "дефрагментации памяти".

TIP: Пояснение. Память делится на две части. Все объекты создаются (и удаляются) только в одной ее половине. Когда наступает время убрать дырки в памяти, все объекты из первой половины переносятся во второю половину. Но копируются уже вплотную друг другу, чтобы дыр не было.

==== Цикл сборки мусора
Описание цикла работы сборщика мусора (работает в фоне, параллельно с самой java-программой)

. Все новосозданные объекты попадают в область Young Generation, а именно в её раздел Eden.
. Когда в Eden заканчивается память, происходит "быстрая" сборка мусора.
. Все объекты пережившие "быструю" сборку мусора попадают в раздел Survival Space, где делятся на поколения.
. Когда в Survival Space заканчивается память, все наиболее старые поколения перемещаются в область Old Generation.
. Наконец, когда в области Old Generation заканчивается место, происходит "полная" уборка мусора.
