= Коллекции

Коллекции или контейнеры - классы, предназначенные для хранения и обработки множества объектов сразу.

Коллекции и их реализации:

. List
.. ArrayList (Список)
.. LinkedList (Связный список)
.. Vector (Вектор)
.. Stack Стэк (стопка)
. Set
.. HashSet (Множество)
.. TreeSet
.. LinkedHashSet
. Queue
.. PriorityQueue (Очередь)
.. ArrayDeque
. Map
.. HashMap (Карта/Словарь)
.. TreeMap
.. HashTable

TIP: Нюанс Java. Коллекции - это классы, реализующие интерфейс Collection.

TIP: Важно! Коллекции не могут хранить примитивные типы (вместо int нужно использовать Integer)

== List
* Collections.unmodifiableList - метод, запрещающий изменять список (добавлять, удалять).
* Collections.disjoint - сравнение двух коллекций на наличие пересечений (одинаковых элементов).

=== Класс ArrayList (Массив)
У класса ArrayList отсутствуют все недостатки, которые есть у массивов. Он умеет:

* Хранить элементы определенного типа
* Динамически менять размер списка
* Добавлять элементы в конец списка
* Вставлять элементы в начало и середину списка
* Удалять элементы из любого места списка

=== Принцип работы ArrayList
* Внутри объекта ArrayList содержится самый обычный массив! И переменная size, которая хранит длину списка.
* Изначально длина массива внутри списка — 10 элементов. А переменная size равна 0.
* Если в список добавить элемент, он будет сохранен в 0-ю ячейку массива, а size увеличится до 1.
* Если добавить еще один элемент, он будет сохранен в 1-ю ячейку, а size снова увеличится на 1 и теперь будет равняться двум.
* Если при добавлении очередного элемента в список в массиве уже нет места, в методе add() происходит следующее:

. Создается новый массив в полтора раза длиннее предыдущего
. В него копируются все элементы из существующего массива
. В объекте ArrayList вместо старого массива сохраняется ссылка на новый.
. В 10-ю ячейку нового массива записывается переданный элемент
. size увеличивается на 1 и теперь будет равняться 11

TIP: Элементы массива внутри объекта ArrayList типа Object!

=== Расширение и уменьшение ArrayList
    Так как при добавлении элемента в полностью заполненный массив происходит создание нового (size() * 1.5) массива, иногда лучше сразу объявить размер массива N.
Но, тогда размер массива не будет уменьшаться автоматически, а будет занимать все N ячеек памяти. Тогда, нужно использовать метод trimToSize(), который уменьшит размер массива до количества заполненных элементов.

=== Работа с ArrayList
WARNING: Нельзя проводить одновременно итерацию (перебор) коллекции и изменение ее элементов (Важное правило).

    Если нарушить правило, то возникнет ошибка "java.util.ConcurrentModificationException".
    Java для удаления элементов во время перебора нужно использовать специальный объект — итератор (класс Iterator). Класс Iterator отвечает за безопасный проход по списку элементов.


== LinkedList (Связный список)

* Самая быстрая операция вставки элементов в середину

== Сравнение коллекций
|===
| Операция            | Метод             | ArrayList    | LinkedList

| Добавление элемента | add(value)        | Быстро       | Очень быстро
| Вставка элемента    | add(index, value) | Медленно     | Очень быстро
| Получение элемента  | get(index)        | Очень быстро | Медленно
| Изменение элемента  | set(index, value) | Очень быстро | Медленно
| Удаление элемента   | remove(index)     | Медленно     | Очень быстро
|===

TIP: Вся работа с ArrayList (по большому счету) сводится к работе с внутренним массивом.
TIP: Вся работа с LinkedList сводится к изменению ссылок.


== Коллекция Set
Коллекция Set создана для хранения множества элементов. Поэтому ее так и называют Set (множество). У этой коллекции есть три особенности

* Наличие ТОЛЬКО трёх операций: добавить элемент, удалить и проверить на наличие в коллекции.
* Отсутствие порядка: у элементов нет индекса, поэтому нет и таких операций как get(), set().
* Все элементы коллекции уникальны.
* Поиск элементов: при выполнении любой из трёх операций, происходит поиск элемента в коллекции. Элементы коллекции и переданный элемент сравниваются сначала по hashCode(), а если hashCode() совпадают, по equals().


== Map (ассоциативный массив)

=== HashMap

TIP: При добавлении элемента с существующим ключём, старое значение затрётся.


== Коллекция Stack
Отличие метода pop() от метода peek():

* pop() возвращает элемент "сверху" стопки (уменьшаю стопку)
* peek() возвращает элемент "сверху" стопки (не удаляя элемент из стопки)

== Enum (Перечисление)
Enum -- тип данных, который состоит из конечного набора значений (9 дней недели, 24 часа в сутках).
На самом деле компилятор во время компиляции класс Enum преобразует в обычный класс, а затем добавляет в него константы, статические методы, private-конструктор

WARNING: От класса Enum невозможно наследоваться.
