= Stream (Потоки)

Класс Stream был создан для того, чтобы можно было легко конструировать цепочки потоков данных.
Stream - это инструмент для поддержки распараллеливания вычислений в потоках. Предоставляет возможность обрабатывать одну или несколько операций, которые могут выполняться последовательно или параллельно (метод parallel или Collection.parallelStream).
Внутри потока данных, данные вообще не меняются. Цепочка промежуточных методов – это хитрый (декларативный) способ указания некой последовательности обработки данных, которая начнет выполняться после вызова терминального (конечного) метода.

Разница между коллекцией и потоками в java в том, что коллекции позволяют работать с отдельными элементами (добавлять элементы, удалять, вставлять в середину), тогда как потоки этого не позволяют, но вместо этого позволяют выполнять функции над данными как одним целом.

== Методы
Все методы потоков (Stream) делятся на два типа:

. Intermediate (промежуточные) - возвращают объект, который имплементируют объект типа Stream.
[source, java]
----
Stream<R> map();
----

. Terminal (конечные) - возвращают значение, тип которого отличен от типа Stream.
[source, java]
----
long count();
----