= Полезные классы

== Классы, для стандартной работы
* Math - математические формулы(синусы, логарифмы, квадрат и т.д.)
* TimeUnit - работа с временем (задержки и т.д.)
* StringTokenizer - специальный класс, вся работа которого — разделять строку на подстроки.
* Date - дата, время (DEPRECATED).
* Calendar - дата, время (DEPRECATED).
* java.time — базовый пакет для Java Date Time API (LocalDateTime, LocalTime, Instant, ZonedDateTime и др.).

== Работа с ресурсами в интернете
* URL - работа с ресурсами в интернете.
* URLConnection - загрузка и выгрузка данных из ресурсов в интернете.

== Работа с файлами
* Files - работа с файлами | На смену File (java.nio.file.Files). (Java 7+)
* File - работа с файлами (Java 5+)
* FileInputStream- чтение байтов из файла. (Минус - считывает данные по одному байту. Сколько байтов, столько и обращений для чтения). (Java 5+)
* FileOutputStream - запись байтов в файл. (Минус - записывает данные по одному байту. Сколько байтов, столько и обращений для записи). (Java 5+)
* BufferedInputStream - чтение байтов из файла. (Плюс - считывает данные блоками байтов и временно хранит их в специальном буфере. Меньше обращений для чтения). (Java 5+)
* BufferedOutputStream - запись байтов в файл. (Плюс - записывает данные блоками байтов и временно хранит их в специальном буфере. Меньше обращений для записи). (Java 5+)
