= Коллекции

Важно! Коллекции не могут хранить примитивные типы (вместо int нужно использовать Integer)

== Класс ArrayList
У класса ArrayList отсутствуют все недостатки, которые есть у массивов. Он умеет:

* Хранить элементы определенного типа
* Динамически менять размер списка
* Добавлять элементы в конец списка
* Вставлять элементы в начало и середину списка
* Удалять элементы из любого места списка

== Принцип работы ArrayList
Внутри объекта ArrayList содержится самый обычный массив! И переменная size, которая хранит длину списка.
Изначально длина массива внутри списка — 10 элементов. А переменная size равна 0.
Если в список добавить элемент, он будет сохранен в 0-ю ячейку массива, а size увеличится до 1.
Если добавить еще один элемент, он будет сохранен в 1-ю ячейку, а size снова увеличится на 1 и теперь будет равняться двум.
Если при добавлении очередного элемента в список в массиве уже нет места, в методе add() происходит следующее:

. Создается новый массив в полтора раза длиннее предыдущего
. В него копируются все элементы из существующего массива
. В объекте ArrayList вместо старого массива сохраняется ссылка на новый.
. В 10-ю ячейку нового массива записывается переданный элемент
. size увеличивается на 1 и теперь будет равняться 11
