= ООП (Объектно - ориентированное программирование)

== Абстракция
Абстракция — один из четырех основных принципов объектно-ориентированного программирования. Он подразумевает выделение главных, наиболее значимых характеристик предмета, и наоборот — отбрасывание второстепенных, незначительных.

Выражен в следующих пунктах:

* Возможность создавать абстрактные классы (public abstract class House).
** Класс является абстрактным, если содержит хотя бы 1 абстрактный метод.
* Абстрактный класс может содержать метод без реализации (public abstract int getPi();).
* Наследование от абстрактного класса.
** При наследовании от абстрактного класса, нужно переопределить все унаследованные абстрактные методы (написать реализацию методов).

! Абстрактные классы могут иметь переменные и реализацию методов, но для них множественное наследование запрещено.

== Инкапсуляция
Инкапсуляция - концепция сокрытия данных. Инкапсуляция гарантирует, что ни один класс не может получить прямой доступ к внутренним данным класса и, следовательно, изменить их. Только через вызов методов того же класса, что и изменяемые переменные.
Выражена в следующих пунктах:

* Закрытый доступ для прямого вмешательства над private переменными класса, доступ для просмотра, изменения осуществлён только через методы данного класса.
* Закрытый доступ для прямого использования private методов класса, что позволяет безопасно вносить изменения в такие методы.

== Полиморфизм
Полиморфизм - это концепция сокрытия различных реализаций за одним интерфейсом.
Одно название метода, отличная реализация.

Выражен в следующих пунктах:

* Переопределение методов (Статические методы не переопределяются).
* Приведение типов (Object o = new TestClass()).
* Перегрузка методов (Одно название, но разный набор параметров метода)

== Наследование
Наследование - это концепция при которой дочерний объект наследуют аттрибуты и поведение объекта-родителя.
К наследованию относятся операции "Сужения типа" и "Расширение типа".

! Наследовать можно только не статические методы.

! Набор методов, которые можно вызвать у переменной, определяется типом переменной. А какой именно метод/какая реализация вызовется, определяется типом/классом объекта, ссылку на который хранит переменная.
Например:
[source, java]
----
Animal animal = new Dog();
// Набор методов, которые можно вызвать у переменной формируются на основе класса Animal.
// Какой именно метод/какая реализация вызовется формируется на основе класса Dog.
----

== Интерфейсы
Интерфейс — это разновидность класса. Сильно урезанная, если можно так сказать. У интерфейса, в отличие от класса, не может быть своих переменных (кроме статических). Также нельзя создавать объекты типа Интерфейс

* У интерфейсов все методы public.
* Все методы интерфейсов абстрактные (abstract писать не нужно).
* Интерфейс может наследоваться только от интерфейсов (Множественное наследование, если интерфейсов родителей несколько).
* Класс может наследоваться только от одного класса.
* Класс может наследоваться от интерфейса(-сов) (implements как раз для этого и предназначен).
* В интерфейсах можно объявлять ТОЛЬКО СТАТИЧЕСКИЕ переменные.

Интерфейсы лучше использовать для описания поведения
Пример:
[java, source]
----
//Интерфейс соответствует способности передвигаться
interface Movable
{
   void move(String newAddress);
}
----
----
//Класс Car (машина) обладает реализует способность передвигаться, управляться человеком и перевозить грузы
class Car implements Movable
{
   ...
}
----

! Интерфейсы не могут иметь переменные и |реализации методов(до Java 8)|, и для них множественное наследование разрешено.

* Классы наследуются (extends), а интерфейсы реализуются (implements).
Класс — это, чаще всего модель какого-то конкретного объекта. Интерфейс же больше соответствует не объектам, а их способностям или ролям.


== Сравнение Абстрактных классов и Интерфейсов
Сравнение Абстрактных классов и Интерфейсов (Начиная с Java 8)
|===
| Способность                 | Абстрактные классы	       | Интерфейсы

| Переменные                  |           ЕСТЬ             | НЕТ
| Реализация методов          |           ЕСТЬ             | ЕСТЬ
| Множественное наследование  |           НЕТ              | ЕСТЬ
| Методы без реализации       | с оператором abstract      | ничего добавлять не нужно
| Методы с реализацией        | ничего добавлять не нужно  | с оператором default
|===