= Введение в Gradle Build

== Основы
=== Базовая сборка проекта

Шаг 1. Инициализация проекта (команда gradle init)

Шаг 2. Выбор типа генерируемого проекта:
1. basic (базовая верстка) установлено стоит по умолчанию
2. application (если приложение будет иметь исполняемый файл, например калькулятор)
3. library (если приложение будет опубликовано и использовано другими в качестве зависимости)
4. plugin (если создаём плагин для инструмента Gradle Build)

Шаг 3: Выбор языка программирования (по умолчанию Java)

Шаг 4: Требуется ли генерировать проект с подпроектами

Шаг 5: Выбор языка для скриптов DSL
1. Groovy
2. Kotlin (по умолчанию)

Шаг 6: Выбор тестовых библиотек в соответствии с языком программирования

Шаг 7: Выбор названия проекта
Шаг 8: Выбор корневого пакета
Шаг 8: Выбор версии языка программирования

=== Оболочка Gradle
Чтобы при переключении между проектами с разными версиями Gradle постоянно не переключаться между версиями Gradle
существует Gradle оболочка. Gradle оболочка считывает конфигурацию проекта, содержащую версию Gradle, чтобы использовать нужную.
Файл: gradle-wrapper.properties
Параметр: distributionUrl

Причём можно выбирать между BIN и ALL версиями
* bin - только двоичный код (поэтому легче и рекомендован)
* all - bin + исходники


== Плагины и задачи
=== Плагины
* Плагин - это многократно используемое программное обеспечение, которое предоставляет дополнительную функциональность системе сборки Gradle.
* У каждого подпроекта может быть свой набор плагинов

Плагины используют для:

* Добавления новой конфигурационной модели
* Инициализации новой конфигурации по умолчанию
* Добавления задач

==== Типы плагинов
Gradle поддерживает три типа плагинов:

* Плагины скриптов — повторно используемые или файлы, которые применяются с помощью ..gradle.gradle.ktsapply from:
* Предварительно скомпилированные плагины — упакованный код Kotlin или Groovy, применяемый к блоку.plugins {}
* Двоичные плагины — упакованные и опубликованные плагины (часто из Plugin Portal или Maven), которые применяются вместе с блоком.plugins {}

Большинство современных сборок отдают предпочтение двоичным или предварительно скомпилированным плагинам.

== Задачи
Задачи являются основной единицей работы в Gradle Build

Команда для просмотра всез задач проекта:
./gradlew tasks --all 