= Транзакции

Транзакции — это группа последовательных операций с базой данных, которая представляет собой логическую единицу работы с данными. Транзакция может быть выполнена либо целиком и успешно, соблюдая целостность данных и независимо от параллельно идущих других транзакций, либо не выполнена вообще, и тогда она не должна произвести никакого эффекта. Транзакции обрабатываются транзакционными системами, в процессе работы которых создаётся история транзакций.
Проще: Транзакция — набор операций по работе с базой данных, объединенных в одну атомарную пачку.

== Способы закрытия транзакции
* COMMIT - подтверждаем внесённые изменения
* ROLLBACK - откатываем внесённые изменения

== Уровни изоляции транзакций
Выбирая уровень транзакции, мы пытаемся прийти к консенсусу в выборе между высокой согласованностью данных между транзакциями и скоростью выполнения этих самых транзакций.
Стоит отметить, что самую высокую скорость выполнения и самую низкую согласованность имеет уровень read uncommitted. Самую низкую скорость выполнения и самую высокую согласованность — serializable.

=== Read uncommitted
* Самая плохая согласованность данных
* Самая высокая скорость выполнения транзакций
* Каждая транзакция видит незафиксированные изменения другой транзакции ("грязное чтение"), что формирует ошибочный результат выборки, в случае, есть изменения будут откатаны
* Допускает Феномен "грязного чтения"

Примеры использования:

* Режим отладки (когда во время отладки требуется посмотреть что происходит с базой)
* Нестрогие отчёты

=== Read committed
* Параллельно исполняющиеся транзакции видят только зафиксированные изменения из других транзакций
* Не допускает феномен "грязного чтения"
* Допускает феномен "неповторяющегося чтения"
* Допускает феномен "чтения фантомов"

=== Repeatable read
* Не допускает феномен "неповторяющегося чтения"

=== Serializable
* Транзакции ведут себя как будто ничего более не существует, никакого влияния друг на друга нет
* Не допускает феномен "чтения фантомов".
Суть: Пока одна транзакция не завершит работать с данными, другая транзакция не сможет работать с этими данными - Ошибка "Lock wait timeout exceeded"

=== Уровни по умолчанию
По умолчанию в MySQL стоит repeatable read, а в PostgreSQL — read committed.

== Феномены\Аномалии

=== Феномен "потерянное обновление"
Феномен "потерянное обновление" - это феномен, когда при одновременном изменении одного блока данных разными транзакциями теряются все изменения, кроме последнего.

=== Феномен "грязного чтения"
Феномен "грязного чтения" - это феномен, когда при чтении данных, добавленных или изменённых транзакцией, которая впоследствии не подтвердится (т.е. откатится).

=== Феномен "чтение фантомов"
Феномен "чтение фантомов" - это феномен, когда одна транзакция в ходе своего выполнения несколько раз выбирает множество строк по одним и тем же критериям. Другая транзакция в интервалах между этими выборками добавляет строки или изменяет столбцы некоторых строк, используемых в критериях выборки первой транзакции, и успешно заканчивается. В результате получится, что одни и те же выборки в первой транзакции дают разные множества строк.

=== Феномен "неповторяющиеся чтение"
Феномен "неповторяющиеся чтение" - это феномен, когда при повторном чтении в рамках одной транзакции ранее прочитанные данные оказываются изменёнными.