= Docker

Предисловие

== Виртуализация

Чтобы избежать сложностей классического подхода развёртывания приложений на физических серверах, была изобретена ВИРТУАЛИЗАЦИЯ

Виртуализация - технология, которая позволяет создавать виртуальное представление ресурсов отдельно от аппаратных.

=== Виды виртуализации
* Аппаратная
* Программная
* Контейнерная

==== Аппаратная
Аппаратная виртуализация — виртуализация с поддержкой специальной процессорной архитектуры.
Аппаратная виртуализация — это технология, которая позволяет создавать несколько виртуальных компьютеров, работающих на одном физическом компьютере с помощью специального программного обеспечения, называемого гипервизор.
Аппаратная виртуализация позволяет эмулировать различные операционные системы, такие как Windows, Linux или Android, на одном устройстве.

TIP: Гипервизор служит для управления разделением ресурсов и изоляцией гостевых ОС, существует прослойка между хостовой ОС и ВМ.
Например: Установка ОС не на весь диск, а только на его часть, создав его виртуального представления.

==== Программная
Программная виртуализация — это технология, которая позволяет создавать и управлять виртуальными машинами с помощью специального программного обеспечения, называемого гипервизором. Гипервизор работает на базе хостовой операционной системы, которая выступает в роли посредника между ним и физическим сервером. Программная виртуализация используется реже и в основном при построении виртуальных систем для конечного пользователя, например на домашних компьютерах

==== Контейнерная виртуализация!
Контейнерная виртуализация — это технология, которая позволяет осуществлять виртуализацию на уровне ОС: есть хостовая ОС и специальные механизмы, позволяющие создавать изолированные контейнеры. В роли гипервизора выступает хостовая ОС — она отвечает за разделение ресурсов между контейнерами и обеспечивает их изолированность.

Контейнер —  изолированный процесс, который использует основное ядро ОС. Этот контейнер работает со своим кусочком файловой системы, памятью, ядром и другими ресурсами
Работа с контейнерами помогает решить следующие проблемы:

* Утилизации ресурсов (на одном сервере можно запустить несколько контейнеров).
* Изоляции приложений.
* Установки ОС (по сути, мы используем хостовую ОС).
* Настройки окружения для приложения (можно один раз настроить окружение и быстро клонировать его между контейнерами).

== Почему контейнеры?

Особенности контейнеров:

* Короткий жизненный цикл. Любой контейнер можно остановить, перезапустить или удалить. Данные, которые содержатся в контейнере, тоже пропадут. Поэтому при проектировании приложений, которые подходят для контейнеризации, используют правило: не хранить важные данные в контейнере. Такой подход проектирования называют Stateless.
* Контейнеры маленькие и лёгкие, их объём измеряется в мегабайтах. Так получается, потому что в контейнер упаковывают лишь те процессы и зависимости ОС, которые необходимы для приложения. Легковесные контейнеры занимают мало места на диске и быстро запускаются.
* Контейнеризация обеспечивает изоляцию процессов. Приложения, которые работают внутри контейнера, не имеют доступа к основной ОС.
* Благодаря контейнерам можно перейти с монолита на микросервисную архитектуру.
Не нужно тратиться на гипервизор, и можно запустить больше контейнеров, чем ВМ на одних и тех же ресурсах.
* Контейнеры хранятся в специальных репозиториях, и каждый контейнер содержит всё необходимое окружение для запуска приложения, благодаря чему можно автоматизировать развёртывание приложения на разных хостах.

== Инструмент Docker

Docker - инструмент, предназначенный для лёгкого запуска разных приложений в изолированных контейнерах на одном сервере.
Каждый контейнер полностью изолирован от других, что позволяет настроить окружение для индивидуально.
TIP: Docker является альтернативой развёртыванию приложений на физических серверах.

Преимущества инструмента Docker:

* Сообщество. Существует огромное хранилище контейнеров с открытым исходным кодом, и вы можете скачать готовый образ для конкретной задачи.
* Гибкость. Docker позволяет создавать базовые шаблоны контейнеров (image) и использовать их повторно на различных хостах. Docker-контейнеры можно легко запустить как на локальном устройстве, так и в любой облачной инфраструктуре.
* Скорость развёртывания. Шаблон контейнера содержит всё необходимое окружение и настройки для работы приложения, нам не нужно настраивать всё это каждый раз с нуля.
* Нет проблемы с зависимостями и версиями пакетов. Docker позволяет упаковывать различные языки программирования и стек технологий в контейнер, чем избавляет от проблемы несовместимости разных библиотек и технологий в рамках одного хоста.

=== Детали
1. В ядре Linux уже из коробки есть все необходимые инструменты для создания контейнеров: capabilities (выдача части расширенных прав), namespace (пространство имён), cgroup ...

2. Docker — это очень тонкая прослойка вокруг ядра. Он создаёт контейнер на основе docker image c заданными настройками. Когда вы попросите Docker создать контейнер, он автоматически создаст набор namespaces и cgroup для этого контейнера. Для каждого контейнера своё пространствами имён — своё дерево каталогов, хостнеймы, ресурсы и прочее. За распределением ресурсов следит ОС.

3. По умолчанию Docker при создании контейнера урезает все capabilites внутри него, оставляя только часть возможностей — смену атрибутов UID и GID (chown), kill, chroot и несколько других. Это сделано в целях безопасности, чтобы злоумышленнику не достались все root-права, если бы он смог выбраться из контейнера.

=== Терминология
* Docker Image (Образ) - шаблон для будущих контейнеров. (Как Java класс)
В нём описывается, что должно быть установлено в контейнере и какие действия нужно выполнить при старте контейнера.

* Docker Container (Контейнер) - исполняемый экземпляр образа. Его можно создавать, запускать, останавливать и удалять. (Как Java объект)
Также можно подключать к контейнеру хранилище, объединять контейнеры одной или несколькими сетями.

* Docker Daemon (Демон) - фоновый процесс в ОС, который обрабатывает запросы Docker API и управляет объектами Docker: образами, контейнерами, сетями и томами.

* Docker Client (Клиент) - инструмент командной строки для взаимодействия пользователя с демонами.

* Docker Hub - общедоступный репозиторий = хранилище всех доступных Docker-образов.


=== Как Docker создаёт контейнер
1. Запрос в Docker на создание контейнера
2. Docker автоматически создаёт набор namespaces и cgroup для этого контейнера
* PID Namespace нужны для того, чтобы процессы внутри контейнера не могли видеть процессы, за пределами контейнера.
* Network Namespace нужен для того, чтобы контейнер получил свой сетевой стек, изолированный для других контейнеров.
* Так же со всеми остальными пространствами имён.


Образ - это шаблон для создания контейнера
Контейнер - набор процессов, изолированных от Хостовой ОС, созданный из образа шаблона

== Источники
https://tproger.ru/articles/chto-takoje-docker?ysclid=ln02hv65lw307695525
