= Запуск Java приложения в Docker

Заметки, что я делал

== Подготовка
1. Установил Docker
* Проверил командой 'docker run hello-world'
2. Выкачал контейнер busybox командой 'docker pull busybox'
* Проверил командой 'docker images'
3. Запустил контейнер busybox командой 'docker run busybox echo "Hello"'
* Опция echo "Hello" здесь нужна для наглядности, так как контейнер busybox очень быстро отрабатывает и ничего не отображает
* Также можно увидеть какие контейнеры запускались командой

== Запуск статичного сайта
1. Выкачал образ, заготовленный автором 'docker run prakhar1989/static-site'
2. Запустил контейнер с нужными мне параметрами командой 'docker run -d -p 8888:80 --name static-site prakhar1989/static-site'
3. Проверил, что контейнер запущен и работает в браузере 'http://localhost:8888/'
4. Остановил контейнер

== Запуск Java приложения
1. Выкачал проект TelegramBot
2. Добавил в корень проекта файл Dockerfile
3. Собрал проект через maven командой 'mvn package'
4. Запустил проект для проверки командой 'mvn exec:java -Dexec.mainClass="TelegramBotApi"'
5. Наполнил файл Dockerfile для создания Docker Image
* Была проблема с тем, что локально mvn не создавал папку .mvn. Помогла команда, которую выполнил локально 'mvn -N io.takari:maven:wrapper'
6. Создал Docker Image, где 'java-docker' название image 'docker build --tag java-docker .'
7. Запустил образ командой 'docker run java-docker'
* Была проблема с кодировкой. Помогло изменение формата окончания строки под Linux (в идее внизу справа - CR\LF)

== Пояснения
* Когда я выкачал busybox - я выкачал образ - шаблон для контейнеров
* Командой 'docker run' я создал контейнер, а уточнением 'busybox', я указал по какому шаблону создавать контейнер


== Команды
* 'docker ps' - показывает запущенные контейнеры
* 'docker ps -a' - показывает список контейнеров, которые запускали в принципе
* 'docker run -it' - команда run с флагом -it подключает интерактивный tty в контейнер, в котором можно запускать сколько угодно много команд внутри
* 'docker rm <CONTAINER ID> - позволяет удалять контейнер по его id
* 'docker run -d -P --name static-site prakhar1989/static-site'
** '-d' - открепит терминал (можно закрыть терминал и процесс контейнера не остановиться)
** '-P' - сделает порты публичными и случайными
** '-name' - чтобы задать имя, которое мы хотим дать контейнеру
** 'docker port <CONTAINER PORT>' - позволяет просмотреть порты используемые контейнером
** '-p' - позволяет задать свои порты (например: 'docker run -p 8888:80 prakhar1989/static-site')
* 'docker stop <CONTAINER ID> - останавливает контейнер по id

== Источники
https://habr.com/ru/articles/310460