= SOLID

SOLID — акроним из названий пяти основных принципов дизайна для ООП, придуманных Робертом Мартином:

* S — Single-responsibility principle
* O — Open-closed principle
* L — Liskov substitution principle
* I — Interface segregation principle
* D — Dependency Inversion Principle

== Single-responsibility principle
Single-responsibility principle — принцип единой ответственности.
Данный принцип гласит, что у класса должна быть только одна цель и единственное назначение.

== Open-closed principle
Open-closed principle — принцип открытости/закрытости.
Он означает, что программные сущности (классы, интерфейсы) должны быть открыты для расширения, но закрыты для модификации.

Например, нам понадобился функционал, схожий с функционалом уже существующего класса Cat, но немного другой. Вместо того чтобы изменять функционал класса Cat, при этом ломая те места, в которых он уже задействован, мы используем наследование или композицию. Как итог — мы добились своей цели с модифицированным функционалом класса Cat, но при этом мы не изменили его и ничего не сломали.

== Interface segregation principle
Interface segregation principle — принцип разделения интерфейса.
Данный принцип гласит, что лучше иметь множество специализированных (узконаправленных) интерфейсов, чем один универсальный.

== Dependency Inversion Principle
Dependency Inversion Principle — принцип инверсии зависимостей.
Принцип говорит о том, что модули верхних уровней не должны зависеть от модулей нижних уровней.

Ещё этот принцип описывают как “абстракция не должна зависеть от деталей, детали должны зависеть от абстракции”.