= Подготовка к 1-й встрече к лекциям от Дениса Розина

== Подкаст "Миграция БД и импортозамещение ПО: как положить прод и поднять обратно"
Тема для обсуждения: Что значит «системный анализ»? Как это «мыслить системно»?

Тезисы:

* Решение команды из подкаста переносить данные через интерфейс
* База данных команды не соответствовала БД Майкрософта
* Объём данных миграции - 5 лет обращений, в том числе файлы - 45 тыс. активных записей и 5 млн. архивных записей
* После 3 млн. записей их решение "легло" и нужно было восстанавливать систему

Почему выбрали решение выполнять миграцию через API:

* Со стороны разработчиков не нужно было делать никаких доп. доработок (необходимые методы уже существовали)
* Не было времени на разработку другого решения

Как проводили аварийные работы:

* Сначала полностью изолировали "наш" фронт, чтобы остановить поток запросов и стабилизировать БД
* Исследовали проблему
* Нашли критическую ошибку уязвимость в арх-ру самих запросов
* Нашли "Проблемные" запросы (без фильтрации) ОПИСАНО НИЖЕ
* Рест сначала фильтровал 3 млн. записей (по сроку - сверху старые), а потом из них отбирал необходимые для пагинации (и так каждый раз)
* Первое решение - Добавление индексов
** Индексы в БД - это такая специальная структура данных, которая позволяет ускорять операции поиска и выборки.
** Индексы делают "дубли" записей
** Индексы замедляют скорость выполнения операций записи и обновления
** Неправильно спроектированные индексы ЗАМЕДЛЯЮТ работу поиска
* Второе решение: переработали логику работы с данными через интерфейс
** Чётко раздели рест на 2 сценария: поиск и фильтрацию
* Восстанавливали систему всей командой с чёткой фиксацией всех попыток
* Метрики позволили сформировать ряд гипотез
* Начали проводить проверку по каждой гипотезе, в том числе стресс-нагрузкой

Почему такая проблема произошла:

* Аналитики не предусмотрели достаточного набора нефункциональных требований: с отказоустойчивости, пропускной способности для такого порядка данных
* Разработчики не реализовали защитный механизм против потенциально опасных запросов
* Тестировщики ограничились проверкой функциональных сценариев, но не охватили нагрузочное тестирование

Итоговые рекомендация при разработке НЕфункциональных требований:

* Требование к производительности - запрос выполняется не больше 150 мс.
* Требование к затратам ЦПУ в пиковые нагрузки
* Выгружать большие объёмы данных порционно (частное решение)


По архитектуре:
1. Языки программирования
•	Java: Используется для разработки серверной части и бизнес-логики.
•	JavaScript или TypeScript: Применяется для создания интерактивных пользовательских интерфейсов на стороне клиента.
2. Фреймворки и библиотеки
•	Что такое библиотеки? Что такое фреймворк? Какие они бывают? (опционально)