= Вопросы к первой встрече :hardbreaks-option:
== Вреймворки и библиотеки

....
Вопрос: Что такое фреймворки? Что такое библиотека? Какие они бывают?

Фреймворк - это инструмент, который внедряется в проект для построения основы (каркаса) приложения. Он диктует архитектуру и структуру вашего кода,
предоставляя не просто инструменты, а целую экосистему для разработки.
Библиотека — это набор готовых функций, классов и методов, которые вы можете использовать в своем коде для решения конкретных задач.

Фреймворк является сам по себе программой. Он предоставляет готовый функционал и "дырки" (hooks, места для расширения),
куда вы подставляете свой код, и сам решает, когда его выполнить.

Библиотека является лишь блоком кода, который вызывают в конкретном месте, для решения конкретной специализированной задачи.

Они бывают клиентские (frontend), серверные (backend) и комплексные (full-stack)
....

|====
|Критерий       |Библиотека                            |Фреймворк

|Цель           |Дать инструмент для задачи            |Дать структуру для приложения
|Архитектура    |Не навязывает                         |Диктует архитектуру
|Контроль       |Вы контролируете поток                |Фреймворк контролирует поток (IoC)
|Гибкость       |Высокая, берете что нужно             |Меньше, нужно следовать правилам
|Размер         |Обычно меньше, решает одну задачу     |Крупнее, "полный комплект"
|====

== Базовые термины для знаний системному аналитику про Spring

....
Контроллер - Класс в Spring, в котором реализовано REST API (тип запроса, endpoints, возможно права, вх. и вых. сигналы запроса)
Сервис- Класс, в котором реализована бизнес-логика
DTO - форма данных, которую клиент видит\отправляет
POJO (JOOQ) - модель, получаемая из БД
Репозиторий - класс, в котором реализован доступ к данным
Транзакция - атомарная бизнес-операция
Аутентификация - кто есть пользователь (он ли это)
Авторизация - что пользователь может (какие у него есть права)
....



