= Тавры

== Ранние тавры
Раннетаврские племена обитали в предгорном и горном Крыму (X - VI вв. до н. э.)
Этноним "Тавры" считается придуман греками, так как аборигены Крыма приносили в жертву своей богине Деве быков (тавров), но могли и людей.

== Территория
* От Евпатории до Феодосии - северная граница и дальше всё, что ниже неё, кроме Херсонеса и Керчи.
* Тавры делились на 5 субэтнических групп

=== Упоминания
Первые упоминания известны от античных авторов.

* Гомер, называет лестригонами. Также он описывает древний город Телепила и бухту похожую на Балаклавскую.
* Скилак Кариандский (автор 4 века д о н.э.) описывает эллинский город Херсонес, а на остальной земле живут тавры, а в степях скифы.

=== Быт
* Ваяли первые в Крыму человеческие скульптуры, монументальные произведения искусства, диоритовые стелы.
* Вели разбойничий образ жизни морских пиратов (Диадор Сицилийский 1 век до н.э.) Часто устраивали засаду для судов, прячущихся от шторма в Балаклавской бухте.
* Выращивали виноград, карликовую пшеницу, ловили рыбу.
* Обрабатывали бронзу, но ещё использовали каменные орудия тоже, например ножи.
* Использовали посуду из камня и глины (без использования гончарного круга).

== Соседи
* В торговом городе Херсонесе жили Эллины (греки). Тавры с ними не редко торговали.
* Керченский полуостров во 2 половине н.э. принадлежал боспорцам с царём Митридатом. Тавры с ним поддерживали дружественные отношения.
* На севере жили скифы (с которыми тавры периодически воевали).


== Средние тавры

TIP: В Херсонесе и Боспорских городах нередко встречаются изделия с подписями мастеров "тавр". Что говорит о том, что тавры нередко жили в городах других местных народов.

=== Быт
* Окрепли отношения с греческими поселениями. Всё чаще встречаются находки из бронзы (украшения, наплечники, упряжки) и железа (мечи типа акинаков).
* Обычные землянки сменяются одно- и двухкамерными домами.
* Встречаются гончарные печи, система водоотводных каналов.
* Появляется гладкая керамика, без орнамента.
* Крепостные стены строятся из точно подогнанных огромных блоков из камня, без раствора.

=== Политика и география
* С V века до н.э. скифы (опередившие в формировании государственности) начинают теснить тавров и занимать предгорье. Тавры уходят со степей.
* III век до н.э. - Тавры начинают строить неприступные для кочевников (скифов) укрепления. Самое крупной из известных - Харакс на Ай-Тодоре.
* Встречаются факты совместного выступления тавров и скифов против войск Митридата.


== Поздние тавры

=== Изменения
* Горцы стали скотоводами, жители долин земледельцами (выращивали пшеницу, фасоль, горох, ячмень).
* Тавры в борьбе с римлянами начинают использовать мелкоблочную кладку в оборонительных стенах, как это делали римляне И наращивать крепостные пояса, как это делали скифы.
* Над крепостными стенами начинают возводить башни для обстрела врага.

=== Политика и география
* Сохраняются независимые дружеские отношения со скифами (не участвуют в войне с персидским царём Дарием, в отличие от скифов).
* С IV века до н.э скифы уже торгуют с эллинами Херсонеса.
* В III век до н.э тавры вступают в вооруженный конфликт с греками Херсонеса (грекам начинает не хватать земли). Греки начинают возводить вокруг Херсонеса стены с башнями.
* Скифы заняли Керченский полуостров.
* С I века до н.э. главным противником тавров становятся римляне. Тавры теснее объединяются с римлянами.
* Для уничтожения таврской флотилии малых судов Рим направляет к берегам Крыма 40 кораблей и 3 тыс. солдат на борту.


== "Закат" тавров

=== Тезисы
* Есть мнение, что под напором гуннов (IV до н.э.) тавры жители долин были вытеснены в Мангуп, а жители городов смешались с народами, пришедшими и осевшими в Крыму.
* Последнее упоминание о таврах относится к X веку - в этом пору к ним направляются христианские миссионеры. Хотя возможно таврами уже называли не по этнической принадлежности, а по географической.
* С I века н.э. Тавры как отдельный народ начинают растворяться и ассимилироваться среди, в первую очередь скифов, а затем и всех других пришедших и осевших в Крыму народах.

=== Достояние
* Десятками исчисляются количество скифских, римских, греческих, понтийских, а затем и татарских селений, поднявшихся буквально на фундаменте таврских городищ и крепостей.
* Скифы позаимствовали у тавров технологию кладки камней, метод сужения стен кверху, ленточную керамику, погребальный культ.
* Римляне и греки заимствовали у тавров идею построек в виде усечённых пирамид, кроме Крыма, в других греческих колониях и в самой Элладе такого не встречается.
* Боспорские живописцы всё сильнее со временем переходили к таврскому стилю росписи.
* С ~III века н.э. греческий орнамент резко геометризуется и упрощается, под влиянием таврского искусства.
* Верховный идол тавров - Дева чеканится на боспорских монетах вплоть до эпохи ранней (боспорской) империи.