= Киммерийцы
Древний народ перекочивавший в Крым

== Происхождение
* Как этнос киммерийцы сложились к середине 2-го тысячелетия до н.э в Нижнем Поволжье.
* В основе ираноязычный народ.
* Расселились от Белоградца (Болгария) на западе и до Северного Кавказа на востоке. От юга Крыма и до Пензенской области на севере.
* XII-IX вв. до н.э. приход Киммерийцев в Крым.

== Достижения
* На пике рассвета могучее государство, которое одно время владычествовало над всей Малой Азией.
* Способствовали резкому развитию юга Росси.
* Заимствовали технологию обработки чёрных металлов у передовых держав своего времени, тем самым распространили её на Северный Кавказ, Волгу, Поднепровье и даже Центральную Европу.
* "Передали" скифам наследие в области искусства - "звериный стиль".
* Основали город Киммерик на месте нынешней Керчи.

== Быт
* Погребения их скромны, обряды просты.
* Во главе всего общества стояла военная аристократия.
* Прирожденные конники, вооруженная лучшей по тем временам военной техникой (стальные мечи и др.)