= Базы данных

База данных — это набор данных, хранящиеся в структурированном виде.
По сути это просто хранилище неких сведений, не более того. Сами по себе базы данных не представляли бы интереса, если бы не было систем управления базами данных.

== СУБД
Система управления базами данных — это совокупность языковых и программных средств, которая осуществляет доступ к данным, позволяет их создавать, менять и удалять, обеспечивает безопасность данных и т.д.

== Классификация
Основные виды баз данных:

* Реляционные
* Key-value
* Документированные

=== Реляционные базы данных
Реляционными называются базы данных, в основе построения которых лежит реляционная модель(связи).

=== Key-value базы данных
Key-value базы данных – это тип баз данных, которые хранят данные как совокупность пар «ключ-значение», в которых ключ служит уникальным идентификатором.

=== Документированные базы данных
Документоориентированные базы данных – это тип баз данных, направленный на хранение и запрос данных в виде документов, подобном JSON.


== Sql-запросы
=== Скалярные подзапросы
Скалярные подзапросы - это подзапросы, которые возвращают одну строку с одним столбцом.

=== Подзапросы с несколькими строками и одним столбцом
=== Подзапросы с несколькими строками и несколькими столбцами
=== Коррелированные подзапросы
Запросы, которые не могут выполняться автономно (используют оператор "AS")

=== Обобщённое табличное выражение
Обобщённое табличное выражение или CTE (Common Table Expressions) - это временный результирующий набор данных, к которому можно обращаться в последующих запросах. Для написания обобщённого табличного выражения используется оператор WITH.

=== Объединение запросов, оператор UNION
По умолчанию UNION убирает повторения в результирующей таблице. Для отображения с повторением есть необязательный параметр ALL.


== Заметки
За источник взят материал из курса SQL ACADEMY